export default {
  light: {
    Surface: {
      'surface-0': '#2f2f2f',
      'surface-900': '#444444',
      'surface-800': '#5e5e5d',
      'surface-700': '#787776',
      'surface-600': '#919190',
      'surface-500': '#abaaa9',
      'surface-400': '#bbbab9',
      'surface-300': '#cbcaca',
      'surface-200': '#dbdada',
      'surface-100': '#ebebea',
      'surface-50': '#fbfbfb',
      'surface-ground': '#ffffff',
      'surface-section': 'rgba(171, 170, 169, 0.1000)',
      'surface-card': '#ffffff',
      'surface-overlay': 'rgba(0, 0, 0, 0.2000)',
      'surface-border': '#dbdada',
      'surface-hover': '#ebebea',
      'surface-transparent': 'rgba(255, 255, 255, 0.0001)',
    },
    General: {
      colorScheme: '"light"',
      primaryColor: '#188700',
      primaryColorHover: '#136a00',
      primaryColorText: '#ffffff',
      fontFamily: 'Roboto, Inter, Helvetica, Arial, sans-serif',
      fontSize: 14,
      fontWeight: 'normal',
      textColor: 'rgba(0, 0, 0, 0.8000)',
      textSecondaryColor: 'rgba(0, 0, 0, 0.6000)',
      highlightBg: '#188700',
      highlightTextColor: '#ffffff',
      borderRadius: '0.5rem',
      inlineSpacing: '0.5rem',
      disabledOpacity: '0.6',
      dividerColor: '#dbdada',
      divider: '1px solid $dividerColor',
      focusOutlineColor: '#a0e491',
      focusOutline: 'none',
      focusOutlineOffset: 'none',
      focusShadowWidth: 3.5,
      focusShadow: '0 0 0 $focusShadowWidth $focusOutlineColor',
      errorColor: '#e26e63',
      focusOutlineErrorColor: '#f6d4d1',
      focusShadowError: '0 0 0 $focusShadowWidth $focusOutlineErrorColor',
      transitionDuration: '.2s',
      formElementTransition:
        'background-color $transitionDuration, color $transitionDuration, border-color $transitionDuration, box-shadow $transitionDuration',
      maskBg: 'rgba(0, 0, 0, 0.2000)',
      primeIconFontSize: 14,
      loadingIconFontSize: 28,
      actionIconWidth: 28,
      actionIconHeight: 28,
      actionIconBg: 'rgba(255, 255, 255, 0.0001)',
      actionIconColor: 'rgba(0, 0, 0, 0.6000)',
      actionIconBorderColor: 'rgba(255, 255, 255, 0.0001)',
      actionIconBorder: '1px solid $actionIconBorderColor',
      actionIconHoverBg: '#ebebea',
      actionIconHoverColor: 'rgba(0, 0, 0, 0.8000)',
      actionIconHoverBorderColor: 'rgba(255, 255, 255, 0.0001)',
      actionIconBorderRadius: 7,
      actionIconTransition:
        'background-color $transitionDuration, color $transitionDuration, box-shadow $transitionDuration',
      scaleSM: '0.875',
      scaleLG: '1.25',
    },
    Button: {
      Common: {
        buttonHeight: 35,
        buttonHeightSM: 28,
        buttonHeightLG: 49,
        buttonHeightXL: 56,
        buttonPaddingTopBottom: 0,
        buttonPaddingLeftRight: 14,
        buttonPadding: '$buttonPaddingTopBottom $buttonPaddingLeftRight',
        buttonIconOnlyWidth: 35,
        buttonHoverShadowColor: 'rgba(0, 0, 0, 0.2000)',
        buttonHoverShadow: '0 .25rem .25rem 0 $buttonHoverShadowColor',
        roundedButtonBorderRadius: '100px',
      },
      Basic: {
        buttonBg: '#188700',
        buttonTextColor: '#ffffff',
        buttonBorderColor: 'rgba(255, 255, 255, 0.0001)',
        buttonBorder: '1px solid $buttonBorderColor',
        buttonHoverBg: '#136a00',
        buttonHoverTextColor: '#ffffff',
        buttonActiveBg: '#188700',
        buttonActiveTextColor: '#ffffff',
      },
      Disabled: {
        disabledButtonBg: 'rgba(0, 0, 0, 0.1000)',
        disabledButtonTextColor: 'rgba(0, 0, 0, 0.6000)',
        disabledButtonBorderColor: '#dbdada',
      },
      Outlined: {
        outlinedButtonBg: 'rgba(255, 255, 255, 0.0001)',
        outlinedButtonTextColor: '#188700',
        outlinedButtonBorderColor: '#a0e491',
        outlinedButtonHoverBg: 'rgba(255, 255, 255, 0.0001)',
        outlinedButtonHoverTextColor: '#188700',
        outlinedButtonHoverBorderColor: '#188700',
        outlinedButtonActiveBg: 'rgba(255, 255, 255, 0.0001)',
        outlinedButtonActiveTextColor: '#188700',
        outlinedButtonActiveBorderColor: '#a0e491',
      },
      Text: {
        textButtonBg: '#ffffff',
        textButtonTextColor: '#188700',
        textButtonHoverBg: 'rgba(34, 193, 0, 0.1000)',
        textButtonHoverTextColor: '#188700',
        textButtonActiveBg: '#ffffff',
        textButtonActiveTextColor: '#188700',
      },
      Severity: {
        Danger: {
          Basic: {
            dangerButtonBg: '#e26e63',
            dangerButtonTextColor: '#ffffff',
            dangerButtonBorderColor: 'rgba(255, 255, 255, 0.0001)',
            dangerButtonHoverBg: '#db4c3f',
            dangerButtonHoverTextColor: '#ffffff',
            dangerButtonHoverBorderColor: 'rgba(255, 255, 255, 0.0001)',
            dangerButtonActiveBg: '#e26e63',
            dangerButtonActiveTextColor: '#ffffff',
            dangerButtonActiveBorderColor: 'rgba(255, 255, 255, 0.0001)',
          },
          Outlined: {
            dangerOutlinedButtonBg: 'rgba(255, 255, 255, 0.0001)',
            dangerOutlinedButtonTextColor: '#e26e63',
            dangerOutlinedButtonBorderColor: '#efb2ac',
            dangerOutlinedButtonHoverBg: 'rgba(255, 255, 255, 0.0001)',
            dangerOutlinedButtonHoverTextColor: '#e26e63',
            dangerOutlinedButtonHoverBorderColor: '#e26e63',
            dangerOutlinedButtonActiveBg: 'rgba(255, 255, 255, 0.0001)',
            dangerOutlinedButtonActiveTextColor: '#e26e63',
            dangerOutlinedButtonActiveBorderColor: '#efb2ac',
          },
          Text: {
            dangerTextButtonBg: '#ffffff',
            dangerTextButtonTextColor: '#e26e63',
            dangerTextButtonHoverBg: 'rgba(219, 76, 63, 0.1000)',
            dangerTextButtonHoverTextColor: '#e26e63',
            dangerTextButtonActiveBg: '#ffffff',
            dangerTextButtonActiveTextColor: '#e26e63',
          },
        },
        Warning: {
          Basic: {
            warningButtonBg: '#ffb330',
            warningButtonTextColor: '#ffffff',
            warningButtonBorderColor: 'rgba(255, 255, 255, 0.0001)',
            warningButtonHoverBg: '#ffa100',
            warningButtonHoverTextColor: '#ffffff',
            warningButtonHoverBorderColor: 'rgba(255, 255, 255, 0.0001)',
            warningButtonActiveBg: '#ffb330',
            warningButtonActiveTextColor: '#ffffff',
            warningButtonActiveBorderColor: 'rgba(255, 255, 255, 0.0001)',
          },
          Outlined: {
            warningOutlinedButtonBg: 'rgba(255, 255, 255, 0.0001)',
            warningOutlinedButtonTextColor: '#ffb330',
            warningOutlinedButtonBorderColor: '#ffd791',
            warningOutlinedButtonHoverBg: 'rgba(255, 255, 255, 0.0001)',
            warningOutlinedButtonHoverTextColor: '#ffb330',
            warningOutlinedButtonHoverBorderColor: '#ffb330',
            warningOutlinedButtonActiveBg: 'rgba(255, 255, 255, 0.0001)',
            warningOutlinedButtonActiveTextColor: '#ffb330',
            warningOutlinedButtonActiveBorderColor: '#ffd791',
          },
          Text: {
            warningTextButtonBg: '#ffffff',
            warningTextButtonTextColor: '#ffb330',
            warningTextButtonHoverBg: 'rgba(255, 161, 0, 0.1000)',
            warningTextButtonHoverTextColor: '#ffb330',
            warningTextButtonActiveBg: '#ffffff',
            warningTextButtonActiveTextColor: '#ffb330',
          },
        },
        Success: {
          Basic: {
            successButtonBg: '#68c170',
            successButtonTextColor: '#ffffff',
            successButtonBorderColor: 'rgba(255, 255, 255, 0.0001)',
            successButtonHoverBg: '#45b24e',
            successButtonHoverTextColor: '#ffffff',
            successButtonHoverBorderColor: 'rgba(255, 255, 255, 0.0001)',
            successButtonActiveBg: '#68c170',
            successButtonActiveTextColor: '#ffffff',
            successButtonActiveBorderColor: 'rgba(255, 255, 255, 0.0001)',
          },
          Outlined: {
            successOutlinedButtonBg: 'rgba(255, 255, 255, 0.0001)',
            successOutlinedButtonTextColor: '#68c170',
            successOutlinedButtonBorderColor: '#afdeb3',
            successOutlinedButtonHoverBg: 'rgba(255, 255, 255, 0.0001)',
            successOutlinedButtonHoverTextColor: '#68c170',
            successOutlinedButtonHoverBorderColor: '#68c170',
            successOutlinedButtonActiveBg: 'rgba(255, 255, 255, 0.0001)',
            successOutlinedButtonActiveTextColor: '#68c170',
            successOutlinedButtonActiveBorderColor: '#afdeb3',
          },
          Text: {
            successTextButtonBg: '#ffffff',
            successTextButtonTextColor: '#68c170',
            successTextButtonHoverBg: 'rgba(69, 178, 78, 0.1000)',
            successTextButtonHoverTextColor: '#68c170',
            successTextButtonActiveBg: '#ffffff',
            successTextButtonActiveTextColor: '#68c170',
          },
        },
        Info: {
          Basic: {
            infoButtonBg: '#49a2ef',
            infoButtonTextColor: '#ffffff',
            infoButtonBorderColor: 'rgba(255, 255, 255, 0.0001)',
            infoButtonHoverBg: '#1f8ceb',
            infoButtonHoverTextColor: '#ffffff',
            infoButtonHoverBorderColor: 'rgba(255, 255, 255, 0.0001)',
            infoButtonActiveBg: '#49a2ef',
            infoButtonActiveTextColor: '#ffffff',
            infoButtonActiveBorderColor: 'rgba(255, 255, 255, 0.0001)',
          },
          Outlined: {
            infoOutlinedButtonBg: 'rgba(255, 255, 255, 0.0001)',
            infoOutlinedButtonTextColor: '#49a2ef',
            infoOutlinedButtonBorderColor: '#9ecdf6',
            infoOutlinedButtonHoverBg: 'rgba(255, 255, 255, 0.0001)',
            infoOutlinedButtonHoverTextColor: '#49a2ef',
            infoOutlinedButtonHoverBorderColor: '#49a2ef',
            infoOutlinedButtonActiveBg: 'rgba(255, 255, 255, 0.0001)',
            infoOutlinedButtonActiveTextColor: '#49a2ef',
            infoOutlinedButtonActiveBorderColor: '#9ecdf6',
          },
          Text: {
            infoTextButtonBg: '#ffffff',
            infoTextButtonTextColor: '#49a2ef',
            infoTextButtonHoverBg: 'rgba(31, 140, 235, 0.1000)',
            infoTextButtonHoverTextColor: '#49a2ef',
            infoTextButtonActiveBg: '#ffffff',
            infoTextButtonActiveTextColor: '#49a2ef',
          },
        },
        Help: {
          Basic: {
            helpButtonBg: '#ab77df',
            helpButtonTextColor: '#ffffff',
            helpButtonBorderColor: 'rgba(255, 255, 255, 0.0001)',
            helpButtonHoverBg: '#9757d7',
            helpButtonHoverTextColor: '#ffffff',
            helpButtonHoverBorderColor: 'rgba(255, 255, 255, 0.0001)',
            helpButtonActiveBg: '#ab77df',
            helpButtonActiveTextColor: '#ffffff',
            helpButtonActiveBorderColor: 'rgba(255, 255, 255, 0.0001)',
          },
          Outlined: {
            helpOutlinedButtonBg: 'rgba(255, 255, 255, 0.0001)',
            helpOutlinedButtonTextColor: '#ab77df',
            helpOutlinedButtonBorderColor: '#d2b7ee',
            helpOutlinedButtonHoverBg: 'rgba(255, 255, 255, 0.0001)',
            helpOutlinedButtonHoverTextColor: '#ab77df',
            helpOutlinedButtonHoverBorderColor: '#ab77df',
            helpOutlinedButtonActiveBg: 'rgba(255, 255, 255, 0.0001)',
            helpOutlinedButtonActiveTextColor: '#ab77df',
            helpOutlinedButtonActiveBorderColor: '#d2b7ee',
          },
          Text: {
            helpTextButtonBg: '#ffffff',
            helpTextButtonTextColor: '#ab77df',
            helpTextButtonHoverBg: 'rgba(151, 87, 215, 0.1000)',
            helpTextButtonHoverTextColor: '#ab77df',
            helpTextButtonActiveBg: '#ffffff',
            helpTextButtonActiveTextColor: '#ab77df',
          },
        },
      },
    },
    Misc: {
      Tag: {
        tagHeight: '1.5rem',
        tagFontSize: '0.875rem',
        tagPadding: '0.07rem 0.5rem',
      },
      Skeleton: {
        skeletonBg: '#dbdada',
        skeletonAnimationBg: 'rgba(255, 255, 255, 0.1)',
      },
      Badge: {
        badgeBg: '#188700',
        badgeTextColor: '#ffffff',
        badgeMinWidth: 21,
        badgeHeight: 21,
        badgeFontWeight: 'bold',
        badgeFontSize: 10.5,
        badgeDotSize: 7,
      },
      Chip: {
        chipHeight: 24.5,
        chipBg: '{black.10}',
        chipTextColor: '{black.80}',
        chipBorderRadius: '0.25rem',
        chipBorderColor: 'rgba(255, 255, 255, 0.0001)',
        chipBorder: '1px solid $chipBorderColor',
        chipPaddingTopBottom: 0,
        chipPaddingLeftRight: '0.5rem',
        chipPadding: '$chipPaddingTopBottom $chipPaddingLeftRight',
      },
      Avatar: {
        avatarBg: '#188700',
        avatarTextColor: '#ffffff',
        avatarBorderColor: '#dbdada',
        avatarBorder: '1px solid $avatarBorderColor',
      },
      ProgressBar: {
        progressBarHeight: 14,
        progressBarBorder: 'none',
        progressBarBg: 'rgba(0, 0, 0, 0.1000)',
        progressBarValueBg: '#188700',
        progressBarValueTextColor: '#ffffff',
      },
    },
    Overlay: {
      Tooltip: {
        tooltipBg: '#5e5e5d',
        tooltipTextColor: '#ffffff',
        tooltipPaddingTopBottom: 7,
        tooltipPaddingLeftRight: 14,
        tooltipPadding: '$tooltipPaddingTopBottom $tooltipPaddingLeftRight',
      },
      Overlay: {
        overlayContentBorderColor: '#dbdada',
        overlayContentBorder: '1px solid $overlayContentBorderColor',
        overlayContentBg: '#ffffff',
        overlayContainerShadowColor: 'rgba(0, 0, 0, 0.2000)',
        overlayContainerShadow:
          '0 .25rem .25rem 0 $overlayContainerShadowColor',
      },
      Dialog: {
        Header: {
          dialogHeaderBg: '#ffffff',
          dialogHeaderBorderColor: '#dbdada',
          dialogHeaderBorder: '1px solid $dialogHeaderBorderColor',
          dialogHeaderTextColor: 'rgba(0, 0, 0, 0.8000)',
          dialogHeaderFontWeight: 'bold',
          dialogHeaderFontSize: 17.5,
          dialogHeaderIconPadding: 7,
          dialogHeaderPaddingTopBottom: 14,
          dialogHeaderPaddingLeftRight: 21,
          dialogHeaderPadding:
            '$dialogHeaderPaddingLeftRight $dialogHeaderPaddingLeftRight $dialogHeaderPaddingTopBottom',
        },
        Body: {
          dialogContentPaddingTopBottom: 21,
          dialogContentPaddingLeftRight: 21,
          dialogContentPadding:
            '$dialogContentPaddingTopBottom $dialogContentPaddingLeftRight',
        },
        Footer: {
          dialogFooterBorderColor: 'rgba(255, 255, 255, 0.0001)',
          dialogFooterBorder: '1px solid $dialogFooterBorderColor',
          dialogFooterPaddingTopBottom: 0,
          dialogFooterPaddingLeftRight: 21,
          dialogFooterPadding:
            '$dialogFooterPaddingTopBottom $dialogFooterPaddingLeftRight $dialogFooterPaddingLeftRight',
          dialogFooterButtonGap: 7,
        },
      },
    },
    Menu: {
      Common: {
        verticalMenuPadding: 3.5,
        menuSeparatorMarginTopBottom: 3.5,
        menuSeparatorMarginLeftRight: 0,
        menuSeparatorMargin:
          '$menuSeparatorMarginTopBottom $menuSeparatorMarginLeftRight',
        menuWidth: 112,
        menuBg: 'rgba(255, 255, 255, 0.0001)',
        menuBorderColor: 'rgba(255, 255, 255, 0.0001)',
        menuBorder: 'none',
        menuTextColor: 'rgba(0, 0, 0, 0.6000)',
        menuNodeChildrenPadding: 10.5,
      },
      Item: {
        menuitemPaddingTopBottom: 7,
        menuitemPaddingLeftRight: 10.5,
        menuitemPadding: '$menuitemPaddingTopBottom $menuitemPaddingLeftRight',
        menuitemSpacing: 3.5,
        menuitemBorderRadius: 7,
        menuitemIconColor: 'rgba(0, 0, 0, 0.8000)',
        menuitemBg: 'rgba(255, 255, 255, 0.0001)',
        menuitemBorderColor: 'rgba(255, 255, 255, 0.0001)',
        menuitemBorder: '1px solid $menuitemBorderColor',
        menuitemTextColor: 'rgba(0, 0, 0, 0.8000)',
        menuitemHoverBg: '#ebebea',
        menuitemHoverTextColor: 'rgba(0, 0, 0, 0.8000)',
        menuitemHoverIconColor: 'rgba(0, 0, 0, 0.8000)',
        menuitemFocusBg: '#ebebea',
        menuitemFocusTextColor: 'rgba(0, 0, 0, 0.8000)',
        menuitemFocusIconColor: 'rgba(0, 0, 0, 0.8000)',
        menuitemActiveBg: '#188700',
        menuitemActiveTextColor: '#ffffff',
        menuitemActiveIconColor: '#ffffff',
        menuitemActiveHoverBg: '#136a00',
        menuitemSubmenuIconFontSize: 17.5,
      },
      Submenu: {
        submenuHeaderMargin: 3.5,
        submenuHeaderPadding:
          '$menuitemPaddingTopBottom $menuitemPaddingLeftRight',
        submenuHeaderBg: 'rgba(255, 255, 255, 0.0001)',
        submenuHeaderTextColor: 'rgba(0, 0, 0, 0.6000)',
        submenuHeaderFontSize: 12.25,
        submenuHeaderFontWeight: 'bold',
        submenuHeaderBorderRadius: 7,
        submenuHeaderBorderColor: 'rgba(255, 255, 255, 0.0001)',
        submenuHeaderBorder: '1px solid $submenuHeaderBorderColor',
      },
      Overlay: {
        overlayMenuBg: '#ffffff',
        overlayMenuBorderColor: '#dbdada',
        overlayMenuBorder: '1px solid $overlayMenuBorderColor',
        overlayMenuShadow: '0 .25rem .25rem 0 $overlayContainerShadowColor',
        overlayMenuPadding: 3.5,
      },
      Breadcrumb: {
        breadcrumbPadding: 0,
        breadcrumbBg: 'rgba(255, 255, 255, 0.0001)',
        breadcrumbBorder: 'none',
        breadcrumbItemTextColor: 'rgba(0, 0, 0, 0.8000)',
        breadcrumbItemIconColor: 'rgba(0, 0, 0, 0.8000)',
        breadcrumbLastItemTextColor: 'rgba(0, 0, 0, 0.8000)',
        breadcrumbLastItemIconColor: 'rgba(0, 0, 0, 0.8000)',
        breadcrumbSeparatorColor: 'rgba(0, 0, 0, 0.8000)',
      },
    },
    Form: {
      InputText: {
        inputPaddingTopBottom: 0,
        inputPaddingLeftRight: 10.5,
        inputPaddingTop: 10.5,
        inputPadding: '$inputPaddingTopBottom $inputPaddingLeftRight',
        inputTextFontSize: 14,
        inputBg: '#ffffff',
        inputTextColor: 'rgba(0, 0, 0, 0.8000)',
        inputIconColor: 'rgba(0, 0, 0, 0.8000)',
        inputBorderColor: '#dbdada',
        inputBorder: '1px solid $inputBorderColor',
        inputHoverBorderColor: '#188700',
        inputFocusBorderColor: '#188700',
        inputErrorBorderColor: '#e26e63',
        inputPlaceholderTextColor: 'rgba(0, 0, 0, 0.6000)',
      },
      InputGroup: {
        inputGroupBg: '#ffffff',
        inputGroupTextColor: 'rgba(0, 0, 0, 0.6000)',
        inputGroupAddOnMinWidth: 35,
      },
      Checkbox: {
        checkboxWidth: 21,
        checkboxHeight: 21,
        checkboxBorder: '$inputBorder',
        checkboxBorderRadius: 3.5,
        checkboxIconFontSize: 14,
        checkboxActiveBorderColor: '#188700',
        checkboxActiveBg: '#188700',
        checkboxIconActiveColor: '#ffffff',
        checkboxActiveHoverBg: '#136a00',
        checkboxIconActiveHoverColor: '#ffffff',
        checkboxActiveHoverBorderColor: '#136a00',
      },
      RadioButton: {
        radiobuttonWidth: 21,
        radiobuttonHeight: 21,
        radiobuttonBorder: '$inputBorder',
        radiobuttonIconSize: 10.5,
        radiobuttonActiveBorderColor: '#188700',
        radiobuttonActiveBg: '#188700',
        radiobuttonIconActiveColor: '#ffffff',
        radiobuttonActiveHoverBg: '#136a00',
        radiobuttonIconActiveHoverColor: '#ffffff',
        radiobuttonActiveHoverBorderColor: '#136a00',
      },
      inputSwitch: {
        inputSwitchWidth: 35,
        inputSwitchHeight: 21,
        inputSwitchBorderRadius: '100px',
        inputSwitchHandleWidth: 14,
        inputSwitchHandleHeight: 14,
        inputSwitchHandleBorderRadius: '100px',
        inputSwitchSliderPadding: 3.5,
        inputSwitchSliderOffBg: '#cbcaca',
        inputSwitchHandleOffBg: '#ffffff',
        inputSwitchSliderOffHoverBg: '#136a00',
        inputSwitchSliderOnBg: '#188700',
        inputSwitchSliderOnHoverBg: '#136a00',
        inputSwitchHandleOnBg: '#ffffff',
      },
      Rating: {
        ratingIconFontSize: 17.5,
        ratingCancelIconColor: 'rgba(0, 0, 0, 0.6000)',
        ratingCancelIconHoverColor: 'rgba(0, 0, 0, 0.8000)',
        ratingStarIconOffColor: 'rgba(0, 0, 0, 0.6000)',
        ratingStarIconOnColor: '#ffb330',
        ratingStarIconHoverColor: '#ffa100',
      },
      InputOpt: {
        inputOptFontSize: 21,
      },
      ToggleButton: {
        toggleButtonBg: 'rgba(0, 0, 0, 0.1000)',
        toggleButtonBorderColor: 'rgba(255, 255, 255, 0.0001)',
        toggleButtonBorder: '1px solid trasparent',
        toggleButtonTextColor: 'rgba(0, 0, 0, 0.6000)',
        toggleButtonIconColor: 'rgba(0, 0, 0, 0.6000)',
        toggleButtonHoverBg: 'rgba(34, 193, 0, 0.1000)',
        toggleButtonHoverBorderColor: 'rgba(255, 255, 255, 0.0001)',
        toggleButtonHoverTextColor: '#188700',
        toggleButtonIconHoverColor: '#188700',
        toggleButtonActiveBg: '#188700',
        toggleButtonActiveBorderColor: 'rgba(255, 255, 255, 0.0001)',
        toggleButtonActiveTextColor: '#ffffff',
        toggleButtonIconActiveColor: '#ffffff',
        toggleButtonActiveHoverBg: '#136a00',
        toggleButtonActiveHoverBorderColor: 'rgba(255, 255, 255, 0.0001)',
        toggleButtonTextActiveHoverColor: '#ffffff',
        toggleButtonIconActiveHoverColor: '#ffffff',
      },
      Slider: {
        sliderBorder: 'none',
        sliderBg: 'rgba(0, 0, 0, 0.1000)',
        sliderHorizontalHeight: 3.5,
        sliderVerticalWidth: 3.5,
        sliderHandleWidth: 17.5,
        sliderHandleHeight: 17.5,
        sliderHandleBg: '#188700',
        sliderHandleHoverBg: '#136a00',
        sliderHandleBorderRadius: 14,
        sliderHandleHoverBorderColor: 'rgba(255, 255, 255, 0.0001)',
        sliderHandleBorder: 'none',
        sliderRangeBg: '#188700',
      },
      SelectButton: {
        selectButtonGroupBg: 'rgba(0, 0, 0, 0.1000)',
        selectButtonGroupPadding: 3.5,
        selectButtonBg: 'rgba(255, 255, 255, 0.0001)',
        selectButtonBorderColor: 'rgba(255, 255, 255, 0.0001)',
        selectButtonBorder: '1px solid trasparent',
        selectButtonBorderRadius: 3.5,
        selectButtonTextColor: 'rgba(0, 0, 0, 0.6000)',
        selectButtonIconColor: 'rgba(0, 0, 0, 0.6000)',
        selectButtonHoverBg: '#ffffff',
        selectButtonHoverBorderColor: 'rgba(255, 255, 255, 0.0001)',
        selectButtonHoverTextColor: 'rgba(0, 0, 0, 0.8000)',
        selectButtonIconHoverColor: 'rgba(0, 0, 0, 0.8000)',
        selectButtonActiveBg: '#ffffff',
        selectButtonActiveBorderColor: 'rgba(255, 255, 255, 0.0001)',
        selectButtonActiveTextColor: '#188700',
        selectButtonIconActiveColor: '#188700',
        selectButtonActiveHoverBg: '#ffffff',
        selectButtonActiveHoverBorderColor: 'rgba(255, 255, 255, 0.0001)',
        selectButtonTextActiveHoverColor: 'rgba(0, 0, 0, 0.8000)',
        selectButtonIconActiveHoverColor: 'rgba(0, 0, 0, 0.8000)',
      },
      Listbox: {
        inputListBg: '#ffffff',
        inputListTextColor: 'rgba(0, 0, 0, 0.6000)',
        inputListBorderColor: '#dbdada',
        inputListBorder: '1px solid $inputListBorderColor',
        inputListPadding: 3.5,
        inputListItemPaddingTopBottom: 7,
        inputListItemPaddingLeftRight: 10.5,
        inputListItemPadding:
          '$inputListItemPaddingTopBottom $inputListItemPaddingLeftRight',
        inputListItemMargin:
          '$menuSeparatorMarginTopBottom $menuSeparatorMarginLeftRight',
        inputListItemBorderColor: 'rgba(255, 255, 255, 0.0001)',
        inputListItemBorder: '1px solid $inputListItemBorderColor',
        inputListItemBorderRadius: 7,
        inputListItemBg: 'rgba(255, 255, 255, 0.0001)',
        inputListItemTextColor: 'rgba(0, 0, 0, 0.8000)',
        inputListItemHoverBg: '#ebebea',
        inputListItemHoverTextColor: 'rgba(0, 0, 0, 0.8000)',
        inputListItemFocusBg: '#ebebea',
        inputListItemFocusTextColor: 'rgba(0, 0, 0, 0.8000)',
        inputListItemFocusShadow: '0 0 0 $focusShadowWidth $focusOutlineColor',
        inputListHeaderPadding:
          '$menuitemPaddingTopBottom $menuitemPaddingLeftRight',
        inputListHeaderMargin: 0,
        inputListHeaderBg: 'rgba(255, 255, 255, 0.0001)',
        inputListHeaderTextColor: 'rgba(0, 0, 0, 0.6000)',
        inputListHeaderBorderColor: 'rgba(255, 255, 255, 0.0001)',
        inputListHeaderBorder: '1px solid $inputListHeaderBorderColor',
        listItemTransition: '.2s',
      },
      Overlay: {
        inputOverlayBg: '#ffffff',
        inputOverlayHeaderBg: 'rgba(255, 255, 255, 0.0001)',
        inputOverlayBorderColor: '#dbdada',
        inputOverlayBorder: '1px solid $inputOverlayBorderColor',
        inputOverlayShadowColor: 'rgba(0, 0, 0, 0.2000)',
        inputOverlayShadow:
          '0 $focusShadowWidth $focusShadowWidth 0 $inputOverlayShadowColor',
      },
      Password: {
        passwordMeterBg: 'rgba(0, 0, 0, 0.1000)',
        passwordWeakBg: '#e26e63',
        passwordMediumBg: '#ffb330',
        passwordStrongBg: '#68c170',
      },
      Calendar: {
        calendarTableMargin: 0,
        calendarPadding: 10.5,
        calendarBg: '#ffffff',
        calendarInlineBg: '#ffffff',
        calendarTextColor: 'rgba(0, 0, 0, 0.8000)',
        calendarBorderColor: '#dbdada',
        calendarBorder: '1px solid $calendarBorderColor',
        calendarOverlayBorderColor: '#dbdada',
        calendarOverlayBorder: '1px solid $calendarOverlayBorderColor',
        calendarHeaderPaddingBottom: 7,
        calendarHeaderPadding: '0 0 $calendarHeaderPaddingBottom',
        calendarHeaderBg: 'rgba(255, 255, 255, 0.0001)',
        calendarInlineHeaderBg: '#ffffff',
        calendarHeaderBorder: 'none',
        calendarHeaderTextColor: 'rgba(0, 0, 0, 0.6000)',
        calendarHeaderFontWeight: 'bold',
        calendarHeaderCellPadding: 3.5,
        calendarMonthYearHeaderHoverTextColor: '#188700',
        calendarCellDatePadding: 3.5,
        calendarCellDateWidth: 28,
        calendarCellDateHeight: 28,
        calendarCellDateBorderRadius: 7,
        calendarCellDateBorderColor: 'rgba(255, 255, 255, 0.0001)',
        calendarCellDateBorder: '1px solid $calendarCellDateBorderColor',
        calendarCellDateHoverBg: '#ebebea',
        calendarCellDateHoverText: 'rgba(0, 0, 0, 0.8000)',
        calendarCellDateTodayBg: 'rgba(255, 255, 255, 0.0001)',
        calendarCellDateTodayBorderColor: '#ebebea',
        calendarCellDateTodayTextColor: 'rgba(0, 0, 0, 0.8000)',
        calendarButtonBarPaddingTop: 0,
        calendarButtonBarPadding: '$calendarButtonBarPaddingTop 0 0',
        calendarTimePickerPadding: 'String value',
        calendarTimePickerElementPadding: 'String value',
        calendarTimePickerTimeFontSize: 17.5,
        calendarBreakpoint: '769px',
        calendarCellDatePaddingSM: 3.5,
      },
    },
    Panel: {
      ScrollPanel: {
        scrollPanelTrackBg: 'rgba(0, 0, 0, 0.1000)',
        scrollPanelTrackBorder: '0 none',
      },
      Divider: {
        dividerHorizontalMarginTopBottom: 14,
        dividerHorizontalMarginLeftRight: 0,
        dividerHorizontalMargin:
          '$dividerHorizontalMarginTopBottom $dividerHorizontalMarginLeftRight',
        dividerHorizontalPaddingTopBottom: 0,
        dividerHorizontalPaddingLeftRight: 14,
        dividerHorizontalPadding:
          '$dividerHorizontalPaddingTopBottom $dividerHorizontalPaddingLeftRight',
        dividerVerticalMarginTopBottom: 0,
        dividerVerticalMarginLeftRight: 14,
        dividerVerticalMargin:
          '$dividerVerticalMarginTopBottom $dividerVerticalMarginLeftRight',
        dividerVerticalPaddingTopBottom: 14,
        dividerVerticalPaddingLeftRight: 0,
        dividerVerticalPadding:
          '$dividerVerticalPaddingTopBottom $dividerVerticalPaddingLeftRight',
        dividerSize: '1px',
      },
      TabView: {
        tabviewNavBg: 'rgba(255, 255, 255, 0.0001)',
        tabviewNavBorderWidth: '1px',
        tabviewNavBorderColor: '#dbdada',
        tabviewNavBorder: '$tabviewNavBorderWidth solid $tabviewNavBorderColor',
        tabviewHeaderSpacing: 21,
        tabviewHeaderBorderWidth: 3.5,
        tabviewHeaderBorderColor: 'rgba(255, 255, 255, 0.0001)',
        tabviewHeaderBorder:
          '$tabviewHeaderBorderWidth solid $tabviewHeaderBorderColor',
        tabviewHeaderBg: 'rgba(255, 255, 255, 0.0001)',
        tabviewHeaderTextColor: 'rgba(0, 0, 0, 0.8000)',
        tabviewHeaderFontWeight: 'normal',
        tabviewHeaderPaddingTopBottom: 14,
        tabviewHeaderPaddingLeftRight: 0,
        tabviewHeaderPadding:
          '$tabviewHeaderPaddingTopBottom $tabviewHeaderPaddingLeftRight',
        tabviewHeaderMargin: '0',
        tabviewHeaderHoverBg: 'rgba(255, 255, 255, 0.0001)',
        tabviewHeaderHoverBorderColor: 'rgba(255, 255, 255, 0.0001)',
        tabviewHeaderHoverTextColor: '#188700',
        tabviewHeaderActiveBg: 'rgba(255, 255, 255, 0.0001)',
        tabviewHeaderActiveBorderColor: '#188700',
        tabviewHeaderActiveTextColor: '#188700',
        tabviewContentBorder: 'none',
        tabviewContentBg: 'rgba(255, 255, 255, 0.0001)',
        tabviewContentTextColor: 'rgba(0, 0, 0, 0.8000)',
        tabviewContentPadding:
          '$tabviewHeaderPaddingTopBottom $tabviewHeaderPaddingLeftRight',
      },
      Panel: {
        Header: {
          panelHeaderBorderColor: '#dbdada',
          panelHeaderBorder: '1px solid $panelHeaderBorderColor',
          panelHeaderBg: '#ffffff',
          panelHeaderTextColor: 'rgba(0, 0, 0, 0.8000)',
          panelHeaderFontWeight: 'bold',
          panelHeaderPaddingTopBottom: 14,
          panelHeaderPaddingLeftRight: 21,
          panelHeaderPadding:
            '$panelHeaderPaddingLeftRight $panelHeaderPaddingLeftRight $panelHeaderPaddingTopBottom',
          panelToggleableHeaderPadding: 0,
          panelHeaderHoverBg: '#ffffff',
          panelHeaderHoverBorderColor: '#ffffff',
          panelHeaderTextHoverColor: '#ffffff',
        },
        Body: {
          panelContentBorderColor: '#dbdada',
          panelContentBorder: '1px solid $panelContentBorderColor',
          panelContentBg: '#ffffff',
          panelContentEvenRowBg: '#ffffff',
          panelContentTextColor: 'rgba(0, 0, 0, 0.8000)',
          panelContentPadding: 14,
        },
        Footer: {
          panelFooterBorderColor: 'rgba(255, 255, 255, 0.0001)',
          panelFooterBg: '#ffffff',
          panelFooterTextColor: 'rgba(0, 0, 0, 0.6000)',
          panelFooterPadding: 0,
          panelFooterBorder: '1px solid $panelHeaderBorderColor',
        },
      },
      Stepper: {
        stepsItemBg: '#ffffff',
        stepsItemBorderColor: '#dbdada',
        stepsItemBorder: '1px solid $stepsItemBorderColor',
        stepsItemTextColor: 'rgba(0, 0, 0, 0.8000)',
        stepsItemFontWeight: '500',
        stepsItemNumberWidth: 21,
        stepsItemNumberHeight: 21,
        stepsItemNumberFontSize: 14,
        stepsItemNumberColor: 'rgba(0, 0, 0, 0.8000)',
        stepsItemNumberBorderRadius: 112,
      },
      Accordion: {
        accordionSpacing: 0,
        accordionHeaderBorderColor: '#dbdada',
        accordionHeaderBorder: '1px solid $accordionHeaderBorderColor',
        accordionHeaderBg: 'rgba(255, 255, 255, 0.0001)',
        accordionHeaderTextColor: 'rgba(0, 0, 0, 0.6000)',
        accordionHeaderFontWeight: '700',
        accordionHeaderPaddingTopBottom: '1rem',
        accordionHeaderPaddingLeftRIght: 0,
        accordionHeaderPadding:
          '$accordionHeaderPaddingTopBottom $accordionHeaderPaddingLeftRIght',
        accordionHeaderHoverBg: 'rgba(255, 255, 255, 0.0001)',
        accordionHeaderHoverBorderColor: '#dbdada',
        accordionHeaderHoverTextColor: 'rgba(0, 0, 0, 0.8000)',
        accordionHeaderActiveBg: 'rgba(255, 255, 255, 0.0001)',
        accordionHeaderActiveBorderColor: '#dbdada',
        accordionHeaderActiveTextColor: 'rgba(0, 0, 0, 0.8000)',
        accordionHeaderActiveHoverBg: 'rgba(255, 255, 255, 0.0001)',
        accordionHeaderActiveHoverBorderColor: '#dbdada',
        accordionHeaderActiveHoverTextColor: 'rgba(0, 0, 0, 0.8000)',
        accordionContentBorder: 'none',
        accordionContentBg: 'rgba(255, 255, 255, 0.0001)',
        accordionContentTextColor: 'rgba(0, 0, 0, 0.8000)',
        accordionContentPaddingTop: 0,
        accordionContentPaddingRight: 0,
        accordionContentPaddingBottom: 14,
        accordionContentPaddingLeft: 24.5,
        accordionContentPadding:
          '$accordionContentPaddingTop $accordionContentPaddingRight $accordionContentPaddingBottom $accordionContentPaddingLeft',
      },
      Card: {
        cardBg: '#ffffff',
        cardBorderRadius: 7,
        cardBorderColor: '#dbdada',
        cardBorder: '1px solid $cardBorderColor',
        cardTextColor: 'rgba(0, 0, 0, 0.8000)',
        cardTextFontSize: 14,
        cardBodyPadding: 14,
        cardTitleFontSize: 15.75,
        cardTitleFontWeight: '700',
        cardSubTitleFontSize: 12.25,
        cardSubTitleFontWeight: '400',
        cardSubTitleColor: 'rgba(0, 0, 0, 0.6000)',
        cardContentPaddingTop: 14,
        cardContentPadding: '$cardContentPaddingTop 0 0',
        cardFooterPaddingTop: 14,
        cardFooterPadding: '$cardFooterPaddingTop 0 0',
        cardShadow: '0 .25rem .25rem 0 $overlayContainerShadowColor',
      },
    },
    Message: {
      Toast: {
        toastIconFontSize: 28,
        toastMessageTextMargin: 0,
        toastMargin: 3.5,
        toastPadding: 14,
        toastBorderWidth: 3.5,
        toastShadow: '0 .25rem .25rem 0 $overlayContainerShadowColor',
        toastOpacity: '1',
        toastTitleFontWeight: 'bold',
        toastDetailMargin: 0,
      },
      Messages: {
        messageMargin: 0,
        messagePadding: 14,
        messageBorderWidth: 3.5,
        messageIconFontSize: 28,
        messageTextFontSize: 14,
        messageTextFontWeight: 'normal',
        messageTextColor: 'rgba(0, 0, 0, 0.8000)',
        messageTextSummaryFontSize: 14,
        messageTextSummaryFontWeight: 'bold',
        messageTextSummaryColor: 'rgba(0, 0, 0, 0.8000)',
        messageTextDetailFontSize: 12.25,
        messageTextDetailFontWeight: 'normal',
        messageTextDetailColor: 'rgba(0, 0, 0, 0.6000)',
      },
      InlineMessage: {
        inlineMessagePadding: 14,
        inlineMessageMargin: 0,
        inlineMessageIconFontSize: 28,
        inlineMessageTextFontSize: 14,
        inlineMessageBorderWidth: 3.5,
      },
      Severities: {
        Info: {
          infoMessageBg: '#f4f9fe',
          infoMessageBorderColor: '#9ecdf6',
          infoMessageBorder: '1px solid $infoMessageBorderColor',
          infoMessageIconColor: '#49a2ef',
        },
        Success: {
          successMessageBg: '#f6fbf6',
          successMessageBorderColor: '#afdeb3',
          successMessageBorder: '1px solid $successMessageBorderColor',
          successMessageIconColor: '#68c170',
        },
        Warning: {
          warningMessageBg: '#fffaf2',
          warningMessageBorderColor: '#ffd791',
          warningMessageBorder: '1px solid $warningMessageBorderColor',
          warningMessageIconColor: '#ffb330',
        },
        Danger: {
          dangerMessageBg: '#fdf6f5',
          dangerMessageBorderColor: '#efb2ac',
          dangerMessageBorder: '1px solid $dangerMessageBorderColor',
          dangerMessageIconColor: '#e26e63',
        },
      },
    },
    Data: {
      Paginator: {
        paginatorBg: 'rgba(255, 255, 255, 0.0001)',
        paginatorTextColor: 'rgba(0, 0, 0, 0.8000)',
        paginatorBorderColor: 'rgba(255, 255, 255, 0.0001)',
        paginatorBorder: 'solid $paginatorBorderColor',
        paginatorBorderWidth: '0',
        paginatorPaddingTopBottom: 7,
        paginatorPaddingLeftRight: 0,
        paginatorPadding:
          '$paginatorPaddingTopBottom $paginatorPaddingLeftRight',
        paginatorElementWidth: 35,
        paginatorElementHeight: 35,
        paginatorElementBorderColor: 'rgba(255, 255, 255, 0.0001)',
        paginatorElementBorder: '1px solid $paginatorElementBorderColor',
        paginatorElementBg: 'rgba(255, 255, 255, 0.0001)',
        paginatorElementIconColor: 'rgba(0, 0, 0, 0.6000)',
        paginatorElementHoverBg: '#ebebea',
        paginatorElementHoverBorderColor: 'rgba(255, 255, 255, 0.0001)',
        paginatorElementIconHoverColor: 'rgba(0, 0, 0, 0.8000)',
        paginatorElementBorderRadius: 7,
        paginatorElementMargin: 3.5,
        paginatorElementPadding: 0,
      },
      DataTable: {
        Common: {
          tableResizerHelperBg: '#dbdada',
          tableDragHelperBg: '#ebebea',
          tableCellContentAlignment: 'left',
          tableTopPaginatorBorderWidth: '1px 0 1px 0',
          tableBottomPaginatorBorderWidth: '0 0 0 0',
          tableScaleSM: '.5',
          tableScaleLG: '1.25',
        },
        Header: {
          tableHeaderBorderColor: '#dbdada',
          tableHeaderBorder: '1px solid $tableHeaderBorderColor',
          tableHeaderBorderWidth: '0 0 1px 0',
          tableHeaderBg: '#fbfbfb',
          tableHeaderTextColor: 'rgba(0, 0, 0, 0.8000)',
          tableHeaderFontWeight: '500',
          tableHeaderPaddingTopBottom: 14,
          tableHeaderPaddingLeftRight: 14,
          tableHeaderPadding:
            '$tableHeaderPaddingTopBottom $tableHeaderPaddingLeftRight',
          tableHeaderCellPaddingTopBottom: 14,
          tableHeaderCellPaddingLeftRight: 14,
          tableHeaderCellPadding:
            '$tableHeaderCellPaddingTopBottom $tableHeaderCellPaddingLeftRight',
          tableHeaderCellBg: '#fbfbfb',
          tableHeaderCellTextColor: 'rgba(0, 0, 0, 0.8000)',
          tableHeaderCellIconColor: 'rgba(0, 0, 0, 0.8000)',
          tableHeaderCellFontWeight: '500',
          tableHeaderCellBorderColor: '#dbdada',
          tableHeaderCellBorder: '1px solid $tableHeaderCellBorderColor',
          tableHeaderCellBorderWidth: '0 0 1px 0',
          tableHeaderCellHoverBg: '#ebebea',
          tableHeaderCellTextHoverColor: 'rgba(0, 0, 0, 0.8000)',
          tableHeaderCellIconHoverColor: 'rgba(0, 0, 0, 0.8000)',
          tableHeaderCellHighlightBg: '#ebebea',
          tableHeaderCellHighlightTextColor: 'rgba(0, 0, 0, 0.8000)',
          tableHeaderCellHighlightIconColor: '#188700',
          tableSortableColumnBadgeSize: 17.5,
        },
        Body: {
          tableBodyRowBg: '#ffffff',
          tableBodyRowTextColor: 'rgba(0, 0, 0, 0.8000)',
          tableBodyRowEvenBg: '#fbfbfb',
          tableBodyRowHoverBg: '#ebebea',
          tableBodyRowTextHoverColor: 'rgba(0, 0, 0, 0.8000)',
          tableBodyCellBorderColor: '#dbdada',
          tableBodyCellBorder: '1px solid $tableBodyCellBorderColor',
          tableBodyCellBorderWidth: '0 0 1px 0',
          tableBodyCellPaddingTopBottom: 14,
          tableBodyCellPaddingLeftRight: 14,
          tableBodyCellPadding:
            '$tableBodyCellPaddingTopBottom $tableBodyCellPaddingLeftRight',
          tableBodyCellHighlightBg: '#ebebea',
          tableBodyCellHighlightTextColor: 'rgba(0, 0, 0, 0.8000)',
        },
        Footer: {
          tableFooterCellPaddingTopBottom: 14,
          tableFooterCellPaddingLeftRight: 14,
          tableFooterCellPadding:
            '$tableFooterCellPaddingTopBottom $tableFooterCellPaddingLeftRight',
          tableFooterCellBg: '#fbfbfb',
          tableFooterCellTextColor: 'rgba(0, 0, 0, 0.8000)',
          tableFooterCellFontWeight: '500',
          tableFooterCellBorderColor: '#dbdada',
          tableFooterCellBorder: '1px solid $tableFooterCellBorderColor',
          tableFooterCellBorderWidth: '0 0 1px 0',
          tableFooterBorderColor: '#dbdada',
          tableFooterBorder: '1px solid $tableFooterBorderColor',
          tableFooterBorderWidth: '0 0 1px 0',
          tableFooterBg: '#fbfbfb',
          tableFooterTextColor: 'rgba(0, 0, 0, 0.8000)',
          tableFooterFontWeight: '500',
          tableFooterPaddingTopBottom: 14,
          tableFooterPaddingLeftRight: 14,
          tableFooterPadding:
            '$tableFooterPaddingTopBottom $tableFooterPaddingLeftRight',
        },
      },
      Timeline: {
        timelineTextColor: 'rgba(0, 0, 0, 0.8000)',
        timelineEventMarkerWidth: 14,
        timelineEventMarkerHeight: 14,
        timelineEventMarkerBorderRadius: 112,
        timelineEventConnectorSize: '1px',
        timelineEventMarkerBorderColor: '#188700',
        timelineEventMarkerBorderSize: 3.5,
        timelineEventMarkerBorder:
          '$timelineEventMarkerBorderSize solid $timelineEventMarkerBorderColor',
        timelineEventMarkerBackground: '#ffffff',
        timelineEventColor: '#dbdada',
        timelineVerticalEventContentPaddingTopBottom: 0,
        timelineVerticalEventContentPaddingLeftRight: 7,
        timelineVerticalEventContentPadding:
          '$timelineVerticalEventContentPaddingTopBottom $timelineVerticalEventContentPaddingLeftRight',
        timelineHorizontalEventContentPaddingTopBottom: 7,
        timelineHorizontalEventContentPaddingLeftRight: 0,
        timelineHorizontalEventContentPadding:
          '$timelineHorizontalEventContentPaddingTopBottom $timelineHorizontalEventContentPaddingLeftRight',
      },
    },
    Media: {
      Carousel: {
        carouselIndicatorsPadding: '1rem',
        carouselIndicatorBg: '#dbdada',
        carouselIndicatorHoverBg: '#5e5e5d',
        carouselIndicatorActiveBg: '#5e5e5d',
        carouselIndicatorBorderRadius: '1rem',
        carouselIndicatorWidth: '0.5rem',
        carouselIndicatorHeight: '0.5rem',
      },
      Galleria: {
        Close: {
          galleriaMaskBg: 'rgba(0, 0, 0, 0.2000)',
          galleriaCloseIconMargin: 7,
          galleriaCloseIconFontSize: 28,
          galleriaCloseIconBg: 'rgba(255, 255, 255, 0.0001)',
          galleriaCloseIconColor: 'rgba(255, 255, 255, 0.6000)',
          galleriaCloseIconHoverBg: 'rgba(255, 255, 255, 0.2000)',
          galleriaCloseIconHoverColor: 'rgba(255, 255, 255, 0.8000)',
          galleriaCloseIconWidth: 56,
          galleriaCloseIconHeight: 56,
          galleriaCloseIconBorderRadius: 7,
        },
        Navigator: {
          galleriaItemNavigatorBg: 'rgba(255, 255, 255, 0.0001)',
          galleriaItemNavigatorColor: 'rgba(255, 255, 255, 0.6000)',
          galleriaItemNavigatorMargin: 7,
          galleriaItemNavigatorFontSize: 28,
          galleriaItemNavigatorHoverBg: 'rgba(255, 255, 255, 0.2000)',
          galleriaItemNavigatorHoverColor: 'rgba(255, 255, 255, 0.8000)',
          galleriaItemNavigatorWidth: 56,
          galleriaItemNavigatorHeight: 56,
          galleriaItemNavigatorBorderRadius: 7,
        },
        Caption: {
          galleriaCaptionBg: 'rgba(0, 0, 0, 0.6000)',
          galleriaCaptionTextColor: 'rgba(255, 255, 255, 0.8000)',
          galleriaCaptionPadding: 14,
        },
        Indicators: {
          galleriaIndicatorsPadding: 14,
          galleriaIndicatorBg: 'rgba(255, 255, 255, 0.4000)',
          galleriaIndicatorHoverBg: 'rgba(255, 255, 255, 0.8000)',
          galleriaIndicatorBorderRadius: 14,
          galleriaIndicatorWidth: 7,
          galleriaIndicatorHeight: 7,
          galleriaIndicatorsBgOnItem: 'rgba(255, 255, 255, 0.0001)',
          galleriaIndicatorBgOnItem: 'rgba(255, 255, 255, 0.4000)',
          galleriaIndicatorHoverBgOnItem: 'rgba(255, 255, 255, 0.8000)',
          galleriaIndicatorActiveBgOnItem: 'rgba(255, 255, 255, 0.8000)',
        },
        Thumbnail: {
          galleriaThumbnailContainerBg: '#000000',
          galleriaThumbnailContainerPaddingTopBottom: 7,
          galleriaThumbnailContainerPaddingLeftRight: 7,
          galleriaThumbnailContainerPadding:
            '$galleriaThumbnailContainerPaddingTopBottom $galleriaThumbnailContainerPaddingLeftRight',
          galleriaThumbnailNavigatorBg: 'rgba(255, 255, 255, 0.0001)',
          galleriaThumbnailNavigatorColor: 'rgba(255, 255, 255, 0.6000)',
          galleriaThumbnailNavigatorHoverBg: 'rgba(255, 255, 255, 0.2000)',
          galleriaThumbnailNavigatorHoverColor: 'rgba(255, 255, 255, 0.8000)',
          galleriaThumbnailNavigatorBorderRadius: 7,
          galleriaThumbnailNavigatorWidth: 28,
          galleriaThumbnailNavigatorHeight: 28,
        },
      },
    },
  },
  dark: {
    Surface: {
      'surface-0': '#fbfbfb',
      'surface-900': '#ebebea',
      'surface-800': '#dbdada',
      'surface-700': '#cbcaca',
      'surface-600': '#bbbab9',
      'surface-500': '#abaaa9',
      'surface-400': '#919190',
      'surface-300': '#787776',
      'surface-200': '#5e5e5d',
      'surface-100': '#444444',
      'surface-50': '#2f2f2f',
      'surface-ground': '#1c1b22',
      'surface-section': 'rgba(171, 170, 169, 0.1000)',
      'surface-card': '#1c1b22',
      'surface-overlay': 'rgba(0, 0, 0, 0.4000)',
      'surface-border': '#444444',
      'surface-hover': '#5e5e5d',
      'surface-transparent': 'rgba(0, 0, 0, 0.0001)',
    },
    General: {
      colorScheme: '"dark"',
      primaryColor: '#76d961',
      primaryColorHover: '#a0e491',
      primaryColorText: 'rgba(0, 0, 0, 0.8000)',
      fontFamily: 'Roboto, Inter, Helvetica, Arial, sans-serif',
      fontSize: 14,
      fontWeight: 'normal',
      textColor: '#ffffff',
      textSecondaryColor: 'rgba(255, 255, 255, 0.8000)',
      highlightBg: '#76d961',
      highlightTextColor: 'rgba(0, 0, 0, 0.8000)',
      borderRadius: '0.5rem',
      inlineSpacing: 7,
      disabledOpacity: '0.6',
      dividerColor: '#444444',
      divider: '1px solid $dividerColor',
      focusOutlineColor: '#136a00',
      focusOutline: 'none',
      focusOutlineOffset: 'none',
      focusShadowWidth: 3.5,
      focusShadow: '0 0 0 $focusShadowWidth $focusOutlineColor',
      errorColor: '#e26e63',
      focusOutlineErrorColor: '#782a23',
      focusShadowError: '0 0 0 $focusShadowWidth $focusOutlineErrorColor',
      transitionDuration: '.2s',
      formElementTransition:
        'background-color $transitionDuration, color $transitionDuration, border-color $transitionDuration, box-shadow $transitionDuration',
      maskBg: 'rgba(0, 0, 0, 0.4000)',
      primeIconFontSize: 14,
      loadingIconFontSize: 28,
      actionIconWidth: 28,
      actionIconHeight: 28,
      actionIconBg: 'rgba(0, 0, 0, 0.0001)',
      actionIconColor: 'rgba(255, 255, 255, 0.8000)',
      actionIconBorderColor: 'rgba(0, 0, 0, 0.0001)',
      actionIconBorder: '1px solid $actionIconBorderColor',
      actionIconHoverBg: '#5e5e5d',
      actionIconHoverColor: '#ffffff',
      actionIconHoverBorderColor: 'rgba(0, 0, 0, 0.0001)',
      actionIconBorderRadius: 7,
      actionIconTransition:
        'background-color $transitionDuration, color $transitionDuration, box-shadow $transitionDuration',
      scaleSM: '0.875',
      scaleLG: '1.25',
    },
    Button: {
      Common: {
        buttonHeight: 35,
        buttonHeightSM: 28,
        buttonHeightLG: 49,
        buttonHeightXL: 56,
        buttonPaddingTopBottom: 0,
        buttonPaddingLeftRight: 14,
        buttonPadding: '$buttonPaddingTopBottom $buttonPaddingLeftRight',
        buttonIconOnlyWidth: 35,
        buttonHoverShadowColor: 'rgba(0, 0, 0, 0.4000)',
        buttonHoverShadow: '0 .25rem .25rem 0 $buttonHoverShadowColor',
        roundedButtonBorderRadius: '100px',
      },
      Basic: {
        buttonBg: '#76d961',
        buttonTextColor: 'rgba(0, 0, 0, 0.8000)',
        buttonBorderColor: 'rgba(0, 0, 0, 0.0001)',
        buttonBorder: '1px solid $buttonBorderColor',
        buttonHoverBg: '#a0e491',
        buttonHoverTextColor: 'rgba(0, 0, 0, 0.8000)',
        buttonActiveBg: '#76d961',
        buttonActiveTextColor: 'rgba(0, 0, 0, 0.8000)',
      },
      Disabled: {
        disabledButtonBg: 'rgba(255, 255, 255, 0.2000)',
        disabledButtonTextColor: 'rgba(255, 255, 255, 0.8000)',
        disabledButtonBorderColor: '#444444',
      },
      Outlined: {
        outlinedButtonBg: 'rgba(0, 0, 0, 0.0001)',
        outlinedButtonTextColor: '#76d961',
        outlinedButtonBorderColor: '#136a00',
        outlinedButtonHoverBg: 'rgba(0, 0, 0, 0.0001)',
        outlinedButtonHoverTextColor: '#76d961',
        outlinedButtonHoverBorderColor: '#76d961',
        outlinedButtonActiveBg: 'rgba(0, 0, 0, 0.0001)',
        outlinedButtonActiveTextColor: '#76d961',
        outlinedButtonActiveBorderColor: '#136a00',
      },
      Text: {
        textButtonBg: '#1c1b22',
        textButtonTextColor: '#76d961',
        textButtonHoverBg: 'rgba(34, 193, 0, 0.1000)',
        textButtonHoverTextColor: '#76d961',
        textButtonActiveBg: '#1c1b22',
        textButtonActiveTextColor: '#76d961',
      },
      Severity: {
        Danger: {
          Basic: {
            dangerButtonBg: '#e26e63',
            dangerButtonTextColor: 'rgba(0, 0, 0, 0.8000)',
            dangerButtonBorderColor: 'rgba(0, 0, 0, 0.0001)',
            dangerButtonHoverBg: '#e99088',
            dangerButtonHoverTextColor: 'rgba(0, 0, 0, 0.8000)',
            dangerButtonHoverBorderColor: 'rgba(0, 0, 0, 0.0001)',
            dangerButtonActiveBg: '#e26e63',
            dangerButtonActiveTextColor: 'rgba(0, 0, 0, 0.8000)',
            dangerButtonActiveBorderColor: 'rgba(0, 0, 0, 0.0001)',
          },
          Outlined: {
            dangerOutlinedButtonBg: 'rgba(0, 0, 0, 0.0001)',
            dangerOutlinedButtonTextColor: '#e26e63',
            dangerOutlinedButtonBorderColor: '#782a23',
            dangerOutlinedButtonHoverBg: 'rgba(0, 0, 0, 0.0001)',
            dangerOutlinedButtonHoverTextColor: '#e26e63',
            dangerOutlinedButtonHoverBorderColor: '#e26e63',
            dangerOutlinedButtonActiveBg: 'rgba(0, 0, 0, 0.0001)',
            dangerOutlinedButtonActiveTextColor: '#e26e63',
            dangerOutlinedButtonActiveBorderColor: '#782a23',
          },
          Text: {
            dangerTextButtonBg: '#1c1b22',
            dangerTextButtonTextColor: '#e26e63',
            dangerTextButtonHoverBg: 'rgba(219, 76, 63, 0.1000)',
            dangerTextButtonHoverTextColor: '#e26e63',
            dangerTextButtonActiveBg: '#1c1b22',
            dangerTextButtonActiveTextColor: '#e26e63',
          },
        },
        Warning: {
          Basic: {
            warningButtonBg: '#ffb330',
            warningButtonTextColor: 'rgba(0, 0, 0, 0.8000)',
            warningButtonBorderColor: 'rgba(0, 0, 0, 0.0001)',
            warningButtonHoverBg: '#ffc561',
            warningButtonHoverTextColor: 'rgba(0, 0, 0, 0.8000)',
            warningButtonHoverBorderColor: 'rgba(0, 0, 0, 0.0001)',
            warningButtonActiveBg: '#ffb330',
            warningButtonActiveTextColor: 'rgba(0, 0, 0, 0.8000)',
            warningButtonActiveBorderColor: 'rgba(0, 0, 0, 0.0001)',
          },
          Outlined: {
            warningOutlinedButtonBg: 'rgba(0, 0, 0, 0.0001)',
            warningOutlinedButtonTextColor: '#ffb330',
            warningOutlinedButtonBorderColor: '#8c5900',
            warningOutlinedButtonHoverBg: 'rgba(0, 0, 0, 0.0001)',
            warningOutlinedButtonHoverTextColor: '#ffb330',
            warningOutlinedButtonHoverBorderColor: '#ffb330',
            warningOutlinedButtonActiveBg: 'rgba(0, 0, 0, 0.0001)',
            warningOutlinedButtonActiveTextColor: '#ffb330',
            warningOutlinedButtonActiveBorderColor: '#8c5900',
          },
          Text: {
            warningTextButtonBg: '#1c1b22',
            warningTextButtonTextColor: '#ffb330',
            warningTextButtonHoverBg: 'rgba(255, 161, 0, 0.1000)',
            warningTextButtonHoverTextColor: '#ffb330',
            warningTextButtonActiveBg: '#1c1b22',
            warningTextButtonActiveTextColor: '#ffb330',
          },
        },
        Success: {
          Basic: {
            successButtonBg: '#68c170',
            successButtonTextColor: 'rgba(0, 0, 0, 0.8000)',
            successButtonBorderColor: 'rgba(0, 0, 0, 0.0001)',
            successButtonHoverBg: '#8ccf91',
            successButtonHoverTextColor: 'rgba(0, 0, 0, 0.8000)',
            successButtonHoverBorderColor: 'rgba(0, 0, 0, 0.0001)',
            successButtonActiveBg: '#68c170',
            successButtonActiveTextColor: 'rgba(0, 0, 0, 0.8000)',
            successButtonActiveBorderColor: 'rgba(0, 0, 0, 0.0001)',
          },
          Outlined: {
            successOutlinedButtonBg: 'rgba(0, 0, 0, 0.0001)',
            successOutlinedButtonTextColor: '#68c170',
            successOutlinedButtonBorderColor: '#1c471f',
            successOutlinedButtonHoverBg: 'rgba(0, 0, 0, 0.0001)',
            successOutlinedButtonHoverTextColor: '#68c170',
            successOutlinedButtonHoverBorderColor: '#68c170',
            successOutlinedButtonActiveBg: 'rgba(0, 0, 0, 0.0001)',
            successOutlinedButtonActiveTextColor: '#68c170',
            successOutlinedButtonActiveBorderColor: '#1c471f',
          },
          Text: {
            successTextButtonBg: '#1c1b22',
            successTextButtonTextColor: '#68c170',
            successTextButtonHoverBg: 'rgba(69, 178, 78, 0.1000)',
            successTextButtonHoverTextColor: '#68c170',
            successTextButtonActiveBg: '#1c1b22',
            successTextButtonActiveTextColor: '#68c170',
          },
        },
        Info: {
          Basic: {
            infoButtonBg: '#49a2ef',
            infoButtonTextColor: 'rgba(0, 0, 0, 0.8000)',
            infoButtonBorderColor: 'rgba(0, 0, 0, 0.0001)',
            infoButtonHoverBg: '#1f8ceb',
            infoButtonHoverTextColor: 'rgba(0, 0, 0, 0.8000)',
            infoButtonHoverBorderColor: 'rgba(0, 0, 0, 0.0001)',
            infoButtonActiveBg: '#49a2ef',
            infoButtonActiveTextColor: 'rgba(0, 0, 0, 0.8000)',
            infoButtonActiveBorderColor: 'rgba(0, 0, 0, 0.0001)',
          },
          Outlined: {
            infoOutlinedButtonBg: 'rgba(0, 0, 0, 0.0001)',
            infoOutlinedButtonTextColor: '#49a2ef',
            infoOutlinedButtonBorderColor: '#114d81',
            infoOutlinedButtonHoverBg: 'rgba(0, 0, 0, 0.0001)',
            infoOutlinedButtonHoverTextColor: '#49a2ef',
            infoOutlinedButtonHoverBorderColor: '#49a2ef',
            infoOutlinedButtonActiveBg: 'rgba(0, 0, 0, 0.0001)',
            infoOutlinedButtonActiveTextColor: '#49a2ef',
            infoOutlinedButtonActiveBorderColor: '#114d81',
          },
          Text: {
            infoTextButtonBg: '#1c1b22',
            infoTextButtonTextColor: '#49a2ef',
            infoTextButtonHoverBg: 'rgba(31, 140, 235, 0.1000)',
            infoTextButtonHoverTextColor: '#49a2ef',
            infoTextButtonActiveBg: '#1c1b22',
            infoTextButtonActiveTextColor: '#49a2ef',
          },
        },
        Help: {
          Basic: {
            helpButtonBg: '#ab77df',
            helpButtonTextColor: 'rgba(0, 0, 0, 0.8000)',
            helpButtonBorderColor: 'rgba(0, 0, 0, 0.0001)',
            helpButtonHoverBg: '#9757d7',
            helpButtonHoverTextColor: 'rgba(0, 0, 0, 0.8000)',
            helpButtonHoverBorderColor: 'rgba(0, 0, 0, 0.0001)',
            helpButtonActiveBg: '#ab77df',
            helpButtonActiveTextColor: 'rgba(0, 0, 0, 0.8000)',
            helpButtonActiveBorderColor: 'rgba(0, 0, 0, 0.0001)',
          },
          Outlined: {
            helpOutlinedButtonBg: 'rgba(0, 0, 0, 0.0001)',
            helpOutlinedButtonTextColor: '#ab77df',
            helpOutlinedButtonBorderColor: '#533076',
            helpOutlinedButtonHoverBg: 'rgba(0, 0, 0, 0.0001)',
            helpOutlinedButtonHoverTextColor: '#ab77df',
            helpOutlinedButtonHoverBorderColor: '#ab77df',
            helpOutlinedButtonActiveBg: 'rgba(0, 0, 0, 0.0001)',
            helpOutlinedButtonActiveTextColor: '#ab77df',
            helpOutlinedButtonActiveBorderColor: '#533076',
          },
          Text: {
            helpTextButtonBg: '#1c1b22',
            helpTextButtonTextColor: '#ab77df',
            helpTextButtonHoverBg: 'rgba(151, 87, 215, 0.1000)',
            helpTextButtonHoverTextColor: '#ab77df',
            helpTextButtonActiveBg: '#1c1b22',
            helpTextButtonActiveTextColor: '#ab77df',
          },
        },
      },
    },
    Misc: {
      Tag: {
        tagHeight: '1.1487rem',
        tagFontSize: '0.7656rem',
        tagPadding: '0.06rem 0.44rem',
      },
      Skeleton: {
        skeletonBg: '#444444',
        skeletonAnimationBg: 'rgba(255, 255, 255, 0.1)',
      },
      Badge: {
        badgeBg: '#76d961',
        badgeTextColor: 'rgba(0, 0, 0, 0.8000)',
        badgeMinWidth: 21,
        badgeHeight: 21,
        badgeFontWeight: 'bold',
        badgeFontSize: 10.5,
        badgeDotSize: 7,
      },
      Chip: {
        chipHeight: '5.3125rem',
        chipBg: '{black.10}',
        chipTextColor: '{black.80}',
        chipBorderRadius: '0.25rem',
        chipBorderColor: 'rgba(0, 0, 0, 0.0001)',
        chipBorder: '1px solid $chipBorderColor',
        chipPaddingTopBottom: 0,
        chipPaddingLeftRight: '0.5px',
        chipPadding: '$chipPaddingTopBottom $chipPaddingLeftRight',
      },
      Avatar: {
        avatarBg: '#76d961',
        avatarTextColor: 'rgba(0, 0, 0, 0.8000)',
        avatarBorderColor: '#444444',
        avatarBorder: '1px solid $avatarBorderColor',
      },
      ProgressBar: {
        progressBarHeight: 14,
        progressBarBorder: 'none',
        progressBarBg: 'rgba(255, 255, 255, 0.2000)',
        progressBarValueBg: '#76d961',
        progressBarValueTextColor: 'rgba(0, 0, 0, 0.8000)',
      },
    },
    Overlay: {
      Tooltip: {
        tooltipBg: '#dbdada',
        tooltipTextColor: '#1c1b22',
        tooltipPaddingTopBottom: 7,
        tooltipPaddingLeftRight: 14,
        tooltipPadding: '$tooltipPaddingTopBottom $tooltipPaddingLeftRight',
      },
      Overlay: {
        overlayContentBorderColor: '#444444',
        overlayContentBorder: '1px solid $overlayContentBorderColor',
        overlayContentBg: '#1c1b22',
        overlayContainerShadowColor: 'rgba(0, 0, 0, 0.4000)',
        overlayContainerShadow:
          '0 .25rem .25rem 0 $overlayContainerShadowColor',
      },
      Dialog: {
        Header: {
          dialogHeaderBg: '#1c1b22',
          dialogHeaderBorderColor: '#444444',
          dialogHeaderBorder: '1px solid $dialogHeaderBorderColor',
          dialogHeaderTextColor: '#ffffff',
          dialogHeaderFontWeight: 'bold',
          dialogHeaderFontSize: 17.5,
          dialogHeaderIconPadding: 7,
          dialogHeaderPaddingTopBottom: 14,
          dialogHeaderPaddingLeftRight: 21,
          dialogHeaderPadding:
            '$dialogHeaderPaddingLeftRight $dialogHeaderPaddingLeftRight $dialogHeaderPaddingTopBottom',
        },
        Body: {
          dialogContentPaddingTopBottom: 21,
          dialogContentPaddingLeftRight: 21,
          dialogContentPadding:
            '$dialogContentPaddingTopBottom $dialogContentPaddingLeftRight',
        },
        Footer: {
          dialogFooterBorderColor: 'rgba(0, 0, 0, 0.0001)',
          dialogFooterBorder: '1px solid $dialogFooterBorderColor',
          dialogFooterPaddingTopBottom: 0,
          dialogFooterPaddingLeftRight: 21,
          dialogFooterPadding:
            '$dialogFooterPaddingTopBottom $dialogFooterPaddingLeftRight $dialogFooterPaddingLeftRight',
          dialogFooterButtonGap: 7,
        },
      },
    },
    Menu: {
      Common: {
        verticalMenuPadding: 3.5,
        menuSeparatorMarginTopBottom: 3.5,
        menuSeparatorMarginLeftRight: 0,
        menuSeparatorMargin:
          '$menuSeparatorMarginTopBottom $menuSeparatorMarginLeftRight',
        menuWidth: 112,
        menuBg: 'rgba(0, 0, 0, 0.0001)',
        menuBorderColor: 'rgba(0, 0, 0, 0.0001)',
        menuBorder: 'none',
        menuTextColor: 'rgba(255, 255, 255, 0.8000)',
        menuNodeChildrenPadding: 10.5,
      },
      Item: {
        menuitemPaddingTopBottom: 7,
        menuitemPaddingLeftRight: 10.5,
        menuitemPadding: '$menuitemPaddingTopBottom $menuitemPaddingLeftRight',
        menuitemSpacing: 3.5,
        menuitemBorderRadius: 7,
        menuitemIconColor: 'rgba(255, 255, 255, 0.8000)',
        menuitemBg: 'rgba(0, 0, 0, 0.0001)',
        menuitemBorderColor: 'rgba(0, 0, 0, 0.0001)',
        menuitemBorder: '1px solid $menuitemBorderColor',
        menuitemTextColor: 'rgba(255, 255, 255, 0.8000)',
        menuitemHoverBg: '#5e5e5d',
        menuitemHoverTextColor: '#ffffff',
        menuitemHoverIconColor: '#ffffff',
        menuitemFocusBg: '#5e5e5d',
        menuitemFocusTextColor: '#ffffff',
        menuitemFocusIconColor: '#ffffff',
        menuitemActiveBg: '#76d961',
        menuitemActiveTextColor: 'rgba(0, 0, 0, 0.8000)',
        menuitemActiveIconColor: 'rgba(0, 0, 0, 0.8000)',
        menuitemActiveHoverBg: '#a0e491',
        menuitemSubmenuIconFontSize: 17.5,
      },
      Submenu: {
        submenuHeaderMargin: 3.5,
        submenuHeaderPadding:
          '$menuitemPaddingTopBottom $menuitemPaddingLeftRight',
        submenuHeaderBg: 'rgba(0, 0, 0, 0.0001)',
        submenuHeaderTextColor: 'rgba(255, 255, 255, 0.8000)',
        submenuHeaderFontSize: 12.25,
        submenuHeaderFontWeight: 'bold',
        submenuHeaderBorderRadius: 7,
        submenuHeaderBorderColor: 'rgba(0, 0, 0, 0.0001)',
        submenuHeaderBorder: '1px solid $submenuHeaderBorderColor',
      },
      Overlay: {
        overlayMenuBg: '#1c1b22',
        overlayMenuBorderColor: '#444444',
        overlayMenuBorder: '1px solid $overlayMenuBorderColor',
        overlayMenuShadow: '0 .25rem .25rem 0 $overlayContainerShadowColor',
        overlayMenuPadding: 3.5,
      },
      Breadcrumb: {
        breadcrumbPadding: 0,
        breadcrumbBg: 'rgba(0, 0, 0, 0.0001)',
        breadcrumbBorder: 'none',
        breadcrumbItemTextColor: 'rgba(255, 255, 255, 0.8000)',
        breadcrumbItemIconColor: 'rgba(255, 255, 255, 0.8000)',
        breadcrumbLastItemTextColor: 'rgba(255, 255, 255, 0.8000)',
        breadcrumbLastItemIconColor: 'rgba(255, 255, 255, 0.8000)',
        breadcrumbSeparatorColor: '#ffffff',
      },
    },
    Form: {
      InputText: {
        inputPaddingTopBottom: 0,
        inputPaddingLeftRight: 10.5,
        inputPaddingTop: 10.5,
        inputPadding: '$inputPaddingTopBottom $inputPaddingLeftRight',
        inputTextFontSize: 14,
        inputBg: '#1c1b22',
        inputTextColor: '#ffffff',
        inputIconColor: '#ffffff',
        inputBorderColor: '#444444',
        inputBorder: '1px solid $inputBorderColor',
        inputHoverBorderColor: '#76d961',
        inputFocusBorderColor: '#76d961',
        inputErrorBorderColor: '#e26e63',
        inputPlaceholderTextColor: 'rgba(255, 255, 255, 0.8000)',
      },
      InputGroup: {
        inputGroupBg: '#1c1b22',
        inputGroupTextColor: 'rgba(255, 255, 255, 0.8000)',
        inputGroupAddOnMinWidth: 35,
      },
      Checkbox: {
        checkboxWidth: 21,
        checkboxHeight: 21,
        checkboxBorder: '$inputBorder',
        checkboxBorderRadius: 3.5,
        checkboxIconFontSize: 14,
        checkboxActiveBorderColor: '#76d961',
        checkboxActiveBg: '#76d961',
        checkboxIconActiveColor: 'rgba(0, 0, 0, 0.8000)',
        checkboxActiveHoverBg: '#a0e491',
        checkboxIconActiveHoverColor: 'rgba(0, 0, 0, 0.8000)',
        checkboxActiveHoverBorderColor: '#a0e491',
      },
      RadioButton: {
        radiobuttonWidth: 21,
        radiobuttonHeight: 21,
        radiobuttonBorder: '$inputBorder',
        radiobuttonIconSize: 10.5,
        radiobuttonActiveBorderColor: '#76d961',
        radiobuttonActiveBg: '#76d961',
        radiobuttonIconActiveColor: 'rgba(0, 0, 0, 0.8000)',
        radiobuttonActiveHoverBg: '#a0e491',
        radiobuttonIconActiveHoverColor: 'rgba(0, 0, 0, 0.8000)',
        radiobuttonActiveHoverBorderColor: '#a0e491',
      },
      inputSwitch: {
        inputSwitchWidth: 35,
        inputSwitchHeight: 21,
        inputSwitchBorderRadius: '100px',
        inputSwitchHandleWidth: 14,
        inputSwitchHandleHeight: 14,
        inputSwitchHandleBorderRadius: '100px',
        inputSwitchSliderPadding: 3.5,
        inputSwitchSliderOffBg: '#787776',
        inputSwitchHandleOffBg: '#1c1b22',
        inputSwitchSliderOffHoverBg: '#a0e491',
        inputSwitchSliderOnBg: '#76d961',
        inputSwitchSliderOnHoverBg: '#a0e491',
        inputSwitchHandleOnBg: '#1c1b22',
      },
      Rating: {
        ratingIconFontSize: 17.5,
        ratingCancelIconColor: 'rgba(255, 255, 255, 0.8000)',
        ratingCancelIconHoverColor: '#ffffff',
        ratingStarIconOffColor: 'rgba(255, 255, 255, 0.8000)',
        ratingStarIconOnColor: '#ffb330',
        ratingStarIconHoverColor: '#ffa100',
      },
      InputOpt: {
        inputOptFontSize: 21,
      },
      ToggleButton: {
        toggleButtonBg: 'rgba(255, 255, 255, 0.2000)',
        toggleButtonBorderColor: 'rgba(0, 0, 0, 0.0001)',
        toggleButtonBorder: '1px solid trasparent',
        toggleButtonTextColor: 'rgba(255, 255, 255, 0.8000)',
        toggleButtonIconColor: 'rgba(255, 255, 255, 0.8000)',
        toggleButtonHoverBg: 'rgba(34, 193, 0, 0.1000)',
        toggleButtonHoverBorderColor: 'rgba(0, 0, 0, 0.0001)',
        toggleButtonHoverTextColor: '#76d961',
        toggleButtonIconHoverColor: '#76d961',
        toggleButtonActiveBg: '#76d961',
        toggleButtonActiveBorderColor: 'rgba(0, 0, 0, 0.0001)',
        toggleButtonActiveTextColor: 'rgba(0, 0, 0, 0.8000)',
        toggleButtonIconActiveColor: 'rgba(0, 0, 0, 0.8000)',
        toggleButtonActiveHoverBg: '#a0e491',
        toggleButtonActiveHoverBorderColor: 'rgba(0, 0, 0, 0.0001)',
        toggleButtonTextActiveHoverColor: 'rgba(0, 0, 0, 0.8000)',
        toggleButtonIconActiveHoverColor: 'rgba(0, 0, 0, 0.8000)',
      },
      Slider: {
        sliderBorder: 'none',
        sliderBg: 'rgba(255, 255, 255, 0.2000)',
        sliderHorizontalHeight: 3.5,
        sliderVerticalWidth: 3.5,
        sliderHandleWidth: 17.5,
        sliderHandleHeight: 17.5,
        sliderHandleBg: '#76d961',
        sliderHandleHoverBg: '#a0e491',
        sliderHandleBorderRadius: 14,
        sliderHandleHoverBorderColor: 'rgba(0, 0, 0, 0.0001)',
        sliderHandleBorder: 'none',
        sliderRangeBg: '#76d961',
      },
      SelectButton: {
        selectButtonGroupBg: 'rgba(255, 255, 255, 0.2000)',
        selectButtonGroupPadding: 3.5,
        selectButtonBg: 'rgba(0, 0, 0, 0.0001)',
        selectButtonBorderColor: 'rgba(0, 0, 0, 0.0001)',
        selectButtonBorder: '1px solid trasparent',
        selectButtonBorderRadius: 3.5,
        selectButtonTextColor: 'rgba(255, 255, 255, 0.8000)',
        selectButtonIconColor: 'rgba(255, 255, 255, 0.8000)',
        selectButtonHoverBg: '#1c1b22',
        selectButtonHoverBorderColor: 'rgba(0, 0, 0, 0.0001)',
        selectButtonHoverTextColor: '#ffffff',
        selectButtonIconHoverColor: '#ffffff',
        selectButtonActiveBg: '#1c1b22',
        selectButtonActiveBorderColor: 'rgba(0, 0, 0, 0.0001)',
        selectButtonActiveTextColor: '#76d961',
        selectButtonIconActiveColor: '#76d961',
        selectButtonActiveHoverBg: '#1c1b22',
        selectButtonActiveHoverBorderColor: 'rgba(0, 0, 0, 0.0001)',
        selectButtonTextActiveHoverColor: '#ffffff',
        selectButtonIconActiveHoverColor: '#ffffff',
      },
      Listbox: {
        inputListBg: '#1c1b22',
        inputListTextColor: 'rgba(255, 255, 255, 0.8000)',
        inputListBorderColor: '#444444',
        inputListBorder: '1px solid $inputListBorderColor',
        inputListPadding: 3.5,
        inputListItemPaddingTopBottom: 7,
        inputListItemPaddingLeftRight: 10.5,
        inputListItemPadding:
          '$inputListItemPaddingTopBottom $inputListItemPaddingLeftRight',
        inputListItemMargin:
          '$menuSeparatorMarginTopBottom $menuSeparatorMarginLeftRight',
        inputListItemBorderColor: 'rgba(0, 0, 0, 0.0001)',
        inputListItemBorder: '1px solid $inputListItemBorderColor',
        inputListItemBorderRadius: 7,
        inputListItemBg: 'rgba(0, 0, 0, 0.0001)',
        inputListItemTextColor: 'rgba(255, 255, 255, 0.8000)',
        inputListItemHoverBg: '#5e5e5d',
        inputListItemHoverTextColor: '#ffffff',
        inputListItemFocusBg: '#5e5e5d',
        inputListItemFocusTextColor: '#ffffff',
        inputListItemFocusShadow: '0 0 0 $focusShadowWidth $focusOutlineColor',
        inputListHeaderPadding:
          '$menuitemPaddingTopBottom $menuitemPaddingLeftRight',
        inputListHeaderMargin: 0,
        inputListHeaderBg: 'rgba(0, 0, 0, 0.0001)',
        inputListHeaderTextColor: 'rgba(255, 255, 255, 0.8000)',
        inputListHeaderBorderColor: 'rgba(0, 0, 0, 0.0001)',
        inputListHeaderBorder: '1px solid $inputListHeaderBorderColor',
        listItemTransition: '.2s',
      },
      Overlay: {
        inputOverlayBg: '#1c1b22',
        inputOverlayHeaderBg: 'rgba(0, 0, 0, 0.0001)',
        inputOverlayBorderColor: '#444444',
        inputOverlayBorder: '1px solid $inputOverlayBorderColor',
        inputOverlayShadowColor: 'rgba(0, 0, 0, 0.4000)',
        inputOverlayShadow:
          '0 $focusShadowWidth $focusShadowWidth 0 $inputOverlayShadowColor',
      },
      Password: {
        passwordMeterBg: 'rgba(255, 255, 255, 0.2000)',
        passwordWeakBg: '#e26e63',
        passwordMediumBg: '#ffb330',
        passwordStrongBg: '#68c170',
      },
      Calendar: {
        calendarTableMargin: 0,
        calendarPadding: 10.5,
        calendarBg: '#1c1b22',
        calendarInlineBg: '#1c1b22',
        calendarTextColor: 'rgba(255, 255, 255, 0.8000)',
        calendarBorderColor: '#444444',
        calendarBorder: '1px solid $calendarBorderColor',
        calendarOverlayBorderColor: '#444444',
        calendarOverlayBorder: '1px solid $calendarOverlayBorderColor',
        calendarHeaderPaddingBottom: 7,
        calendarHeaderPadding: '0 0 $calendarHeaderPaddingBottom',
        calendarHeaderBg: 'rgba(0, 0, 0, 0.0001)',
        calendarInlineHeaderBg: '#1c1b22',
        calendarHeaderBorder: 'none',
        calendarHeaderTextColor: 'rgba(255, 255, 255, 0.8000)',
        calendarHeaderFontWeight: 'bold',
        calendarHeaderCellPadding: 3.5,
        calendarMonthYearHeaderHoverTextColor: '#76d961',
        calendarCellDatePadding: 3.5,
        calendarCellDateWidth: 28,
        calendarCellDateHeight: 28,
        calendarCellDateBorderRadius: 7,
        calendarCellDateBorderColor: 'rgba(0, 0, 0, 0.0001)',
        calendarCellDateBorder: '1px solid $calendarCellDateBorderColor',
        calendarCellDateHoverBg: '#5e5e5d',
        calendarCellDateHoverText: '#ffffff',
        calendarCellDateTodayBg: 'rgba(0, 0, 0, 0.0001)',
        calendarCellDateTodayBorderColor: '#5e5e5d',
        calendarCellDateTodayTextColor: 'rgba(255, 255, 255, 0.8000)',
        calendarButtonBarPaddingTop: 0,
        calendarButtonBarPadding: '$calendarButtonBarPaddingTop 0 0',
        calendarTimePickerPadding: 'String value',
        calendarTimePickerElementPadding: 'String value',
        calendarTimePickerTimeFontSize: 17.5,
        calendarBreakpoint: '769px',
        calendarCellDatePaddingSM: 3.5,
      },
    },
    Panel: {
      ScrollPanel: {
        scrollPanelTrackBg: 'rgba(255, 255, 255, 0.2000)',
        scrollPanelTrackBorder: '0 none',
      },
      Divider: {
        dividerHorizontalMarginTopBottom: 14,
        dividerHorizontalMarginLeftRight: 0,
        dividerHorizontalMargin:
          '$dividerHorizontalMarginTopBottom $dividerHorizontalMarginLeftRight',
        dividerHorizontalPaddingTopBottom: 0,
        dividerHorizontalPaddingLeftRight: 14,
        dividerHorizontalPadding:
          '$dividerHorizontalPaddingTopBottom $dividerHorizontalPaddingLeftRight',
        dividerVerticalMarginTopBottom: 0,
        dividerVerticalMarginLeftRight: 14,
        dividerVerticalMargin:
          '$dividerVerticalMarginTopBottom $dividerVerticalMarginLeftRight',
        dividerVerticalPaddingTopBottom: 14,
        dividerVerticalPaddingLeftRight: 0,
        dividerVerticalPadding:
          '$dividerVerticalPaddingTopBottom $dividerVerticalPaddingLeftRight',
        dividerSize: '1px',
      },
      TabView: {
        tabviewNavBg: 'rgba(0, 0, 0, 0.0001)',
        tabviewNavBorderWidth: '1px',
        tabviewNavBorderColor: '#444444',
        tabviewNavBorder: '$tabviewNavBorderWidth solid $tabviewNavBorderColor',
        tabviewHeaderSpacing: 21,
        tabviewHeaderBorderWidth: 3.5,
        tabviewHeaderBorderColor: 'rgba(0, 0, 0, 0.0001)',
        tabviewHeaderBorder:
          '$tabviewHeaderBorderWidth solid $tabviewHeaderBorderColor',
        tabviewHeaderBg: 'rgba(0, 0, 0, 0.0001)',
        tabviewHeaderTextColor: 'rgba(255, 255, 255, 0.8000)',
        tabviewHeaderFontWeight: 'normal',
        tabviewHeaderPaddingTopBottom: 14,
        tabviewHeaderPaddingLeftRight: 0,
        tabviewHeaderPadding:
          '$tabviewHeaderPaddingTopBottom $tabviewHeaderPaddingLeftRight',
        tabviewHeaderMargin: '0',
        tabviewHeaderHoverBg: 'rgba(0, 0, 0, 0.0001)',
        tabviewHeaderHoverBorderColor: 'rgba(0, 0, 0, 0.0001)',
        tabviewHeaderHoverTextColor: '#76d961',
        tabviewHeaderActiveBg: 'rgba(0, 0, 0, 0.0001)',
        tabviewHeaderActiveBorderColor: '#76d961',
        tabviewHeaderActiveTextColor: '#76d961',
        tabviewContentBorder: 'none',
        tabviewContentBg: 'rgba(0, 0, 0, 0.0001)',
        tabviewContentTextColor: 'rgba(255, 255, 255, 0.8000)',
        tabviewContentPadding:
          '$tabviewHeaderPaddingTopBottom $tabviewHeaderPaddingLeftRight',
      },
      Panel: {
        Header: {
          panelHeaderBorderColor: '#444444',
          panelHeaderBorder: '1px solid $panelHeaderBorderColor',
          panelHeaderBg: '#1c1b22',
          panelHeaderTextColor: '#ffffff',
          panelHeaderFontWeight: 'bold',
          panelHeaderPaddingTopBottom: 14,
          panelHeaderPaddingLeftRight: 21,
          panelHeaderPadding:
            '$panelHeaderPaddingLeftRight $panelHeaderPaddingLeftRight $panelHeaderPaddingTopBottom',
          panelToggleableHeaderPadding: 0,
          panelHeaderHoverBg: '#ffffff',
          panelHeaderHoverBorderColor: '#ffffff',
          panelHeaderTextHoverColor: '#ffffff',
        },
        Body: {
          panelContentBorderColor: '#444444',
          panelContentBorder: '1px solid $panelContentBorderColor',
          panelContentBg: '#1c1b22',
          panelContentEvenRowBg: '#ffffff',
          panelContentTextColor: '#ffffff',
          panelContentPadding: 14,
        },
        Footer: {
          panelFooterBorderColor: 'rgba(0, 0, 0, 0.0001)',
          panelFooterBg: '#1c1b22',
          panelFooterTextColor: 'rgba(255, 255, 255, 0.8000)',
          panelFooterPadding: 0,
          panelFooterBorder: '1px solid $panelHeaderBorderColor',
        },
      },
      Stepper: {
        stepsItemBg: '#1c1b22',
        stepsItemBorderColor: '#444444',
        stepsItemBorder: '1px solid $stepsItemBorderColor',
        stepsItemTextColor: '#ffffff',
        stepsItemFontWeight: '500',
        stepsItemNumberWidth: 21,
        stepsItemNumberHeight: 21,
        stepsItemNumberFontSize: 14,
        stepsItemNumberColor: '#ffffff',
        stepsItemNumberBorderRadius: 112,
      },
      Accordion: {
        accordionSpacing: 0,
        accordionHeaderBorderColor: '#444444',
        accordionHeaderBorder: '1px solid $accordionHeaderBorderColor',
        accordionHeaderBg: 'rgba(0, 0, 0, 0.0001)',
        accordionHeaderTextColor: 'rgba(255, 255, 255, 0.8000)',
        accordionHeaderFontWeight: '700',
        accordionHeaderPaddingTopBottom: 14,
        accordionHeaderPaddingLeftRIght: 0,
        accordionHeaderPadding:
          '$accordionHeaderPaddingTopBottom $accordionHeaderPaddingLeftRIght',
        accordionHeaderHoverBg: 'rgba(0, 0, 0, 0.0001)',
        accordionHeaderHoverBorderColor: '#444444',
        accordionHeaderHoverTextColor: '#ffffff',
        accordionHeaderActiveBg: 'rgba(0, 0, 0, 0.0001)',
        accordionHeaderActiveBorderColor: '#444444',
        accordionHeaderActiveTextColor: '#ffffff',
        accordionHeaderActiveHoverBg: 'rgba(0, 0, 0, 0.0001)',
        accordionHeaderActiveHoverBorderColor: '#444444',
        accordionHeaderActiveHoverTextColor: '#ffffff',
        accordionContentBorder: 'none',
        accordionContentBg: 'rgba(0, 0, 0, 0.0001)',
        accordionContentTextColor: '#ffffff',
        accordionContentPaddingTop: 0,
        accordionContentPaddingRight: 0,
        accordionContentPaddingBottom: 14,
        accordionContentPaddingLeft: 24.5,
        accordionContentPadding:
          '$accordionContentPaddingTop $accordionContentPaddingRight $accordionContentPaddingBottom $accordionContentPaddingLeft',
      },
      Card: {
        cardBg: '#1c1b22',
        cardBorderRadius: 7,
        cardBorderColor: '#444444',
        cardBorder: '1px solid $cardBorderColor',
        cardTextColor: '#ffffff',
        cardTextFontSize: 14,
        cardBodyPadding: 14,
        cardTitleFontSize: 15.75,
        cardTitleFontWeight: '700',
        cardSubTitleFontSize: 12.25,
        cardSubTitleFontWeight: '400',
        cardSubTitleColor: 'rgba(255, 255, 255, 0.8000)',
        cardContentPaddingTop: 14,
        cardContentPadding: '$cardContentPaddingTop 0 0',
        cardFooterPaddingTop: 14,
        cardFooterPadding: '$cardFooterPaddingTop 0 0',
        cardShadow: '0 .25rem .25rem 0 $overlayContainerShadowColor',
      },
    },
    Message: {
      Toast: {
        toastIconFontSize: 28,
        toastMessageTextMargin: 0,
        toastMargin: 3.5,
        toastPadding: 14,
        toastBorderWidth: 3.5,
        toastShadow: '0 .25rem .25rem 0 $overlayContainerShadowColor',
        toastOpacity: '1',
        toastTitleFontWeight: 'bold',
        toastDetailMargin: 0,
      },
      Messages: {
        messageMargin: 0,
        messagePadding: 14,
        messageBorderWidth: 3.5,
        messageIconFontSize: 28,
        messageTextFontSize: 14,
        messageTextFontWeight: 'normal',
        messageTextColor: '#ffffff',
        messageTextSummaryFontSize: 14,
        messageTextSummaryFontWeight: 'bold',
        messageTextSummaryColor: '#ffffff',
        messageTextDetailFontSize: 12.25,
        messageTextDetailFontWeight: 'normal',
        messageTextDetailColor: 'rgba(255, 255, 255, 0.8000)',
      },
      InlineMessage: {
        inlineMessagePadding: 14,
        inlineMessageMargin: 0,
        inlineMessageIconFontSize: 28,
        inlineMessageTextFontSize: 14,
        inlineMessageBorderWidth: 3.5,
      },
      Severities: {
        Info: {
          infoMessageBg: '#282d32',
          infoMessageBorderColor: '#114d81',
          infoMessageBorder: '1px solid $infoMessageBorderColor',
          infoMessageIconColor: '#49a2ef',
        },
        Success: {
          successMessageBg: '#2a2f2b',
          successMessageBorderColor: '#1c471f',
          successMessageBorder: '1px solid $successMessageBorderColor',
          successMessageIconColor: '#68c170',
        },
        Warning: {
          warningMessageBg: '#332e27',
          warningMessageBorderColor: '#8c5900',
          warningMessageBorder: '1px solid $warningMessageBorderColor',
          warningMessageIconColor: '#ffb330',
        },
        Danger: {
          dangerMessageBg: '#312a2a',
          dangerMessageBorderColor: '#782a23',
          dangerMessageBorder: '1px solid $dangerMessageBorderColor',
          dangerMessageIconColor: '#e26e63',
        },
      },
    },
    Data: {
      Paginator: {
        paginatorBg: 'rgba(0, 0, 0, 0.0001)',
        paginatorTextColor: '#ffffff',
        paginatorBorderColor: 'rgba(0, 0, 0, 0.0001)',
        paginatorBorder: 'solid $paginatorBorderColor',
        paginatorBorderWidth: '0',
        paginatorPaddingTopBottom: 7,
        paginatorPaddingLeftRight: 0,
        paginatorPadding:
          '$paginatorPaddingTopBottom $paginatorPaddingLeftRight',
        paginatorElementWidth: 35,
        paginatorElementHeight: 35,
        paginatorElementBorderColor: 'rgba(0, 0, 0, 0.0001)',
        paginatorElementBorder: '1px solid $paginatorElementBorderColor',
        paginatorElementBg: 'rgba(0, 0, 0, 0.0001)',
        paginatorElementIconColor: 'rgba(255, 255, 255, 0.8000)',
        paginatorElementHoverBg: '#5e5e5d',
        paginatorElementHoverBorderColor: 'rgba(0, 0, 0, 0.0001)',
        paginatorElementIconHoverColor: '#ffffff',
        paginatorElementBorderRadius: 7,
        paginatorElementMargin: 3.5,
        paginatorElementPadding: 0,
      },
      DataTable: {
        Common: {
          tableResizerHelperBg: '#444444',
          tableDragHelperBg: '#5e5e5d',
          tableCellContentAlignment: 'left',
          tableTopPaginatorBorderWidth: '1px 0 1px 0',
          tableBottomPaginatorBorderWidth: '0 0 0 0',
          tableScaleSM: '.5',
          tableScaleLG: '1.25',
        },
        Header: {
          tableHeaderBorderColor: '#444444',
          tableHeaderBorder: '1px solid $tableHeaderBorderColor',
          tableHeaderBorderWidth: '0 0 1px 0',
          tableHeaderBg: '#2f2f2f',
          tableHeaderTextColor: '#ffffff',
          tableHeaderFontWeight: '500',
          tableHeaderPaddingTopBottom: 14,
          tableHeaderPaddingLeftRight: 14,
          tableHeaderPadding:
            '$tableHeaderPaddingTopBottom $tableHeaderPaddingLeftRight',
          tableHeaderCellPaddingTopBottom: 14,
          tableHeaderCellPaddingLeftRight: 14,
          tableHeaderCellPadding:
            '$tableHeaderCellPaddingTopBottom $tableHeaderCellPaddingLeftRight',
          tableHeaderCellBg: '#2f2f2f',
          tableHeaderCellTextColor: '#ffffff',
          tableHeaderCellIconColor: '#ffffff',
          tableHeaderCellFontWeight: '500',
          tableHeaderCellBorderColor: '#444444',
          tableHeaderCellBorder: '1px solid $tableHeaderCellBorderColor',
          tableHeaderCellBorderWidth: '0 0 1px 0',
          tableHeaderCellHoverBg: '#5e5e5d',
          tableHeaderCellTextHoverColor: '#ffffff',
          tableHeaderCellIconHoverColor: '#ffffff',
          tableHeaderCellHighlightBg: '#5e5e5d',
          tableHeaderCellHighlightTextColor: '#ffffff',
          tableHeaderCellHighlightIconColor: '#76d961',
          tableSortableColumnBadgeSize: 17.5,
        },
        Body: {
          tableBodyRowBg: '#1c1b22',
          tableBodyRowTextColor: '#ffffff',
          tableBodyRowEvenBg: '#2f2f2f',
          tableBodyRowHoverBg: '#5e5e5d',
          tableBodyRowTextHoverColor: '#ffffff',
          tableBodyCellBorderColor: '#444444',
          tableBodyCellBorder: '1px solid $tableBodyCellBorderColor',
          tableBodyCellBorderWidth: '0 0 1px 0',
          tableBodyCellPaddingTopBottom: 14,
          tableBodyCellPaddingLeftRight: 14,
          tableBodyCellPadding:
            '$tableBodyCellPaddingTopBottom $tableBodyCellPaddingLeftRight',
          tableBodyCellHighlightBg: '#5e5e5d',
          tableBodyCellHighlightTextColor: '#ffffff',
        },
        Footer: {
          tableFooterCellPaddingTopBottom: 14,
          tableFooterCellPaddingLeftRight: 14,
          tableFooterCellPadding:
            '$tableFooterCellPaddingTopBottom $tableFooterCellPaddingLeftRight',
          tableFooterCellBg: '#2f2f2f',
          tableFooterCellTextColor: '#ffffff',
          tableFooterCellFontWeight: '500',
          tableFooterCellBorderColor: '#444444',
          tableFooterCellBorder: '1px solid $tableFooterCellBorderColor',
          tableFooterCellBorderWidth: '0 0 1px 0',
          tableFooterBorderColor: '#444444',
          tableFooterBorder: '1px solid $tableFooterBorderColor',
          tableFooterBorderWidth: '0 0 1px 0',
          tableFooterBg: '#2f2f2f',
          tableFooterTextColor: '#ffffff',
          tableFooterFontWeight: '500',
          tableFooterPaddingTopBottom: 14,
          tableFooterPaddingLeftRight: 14,
          tableFooterPadding:
            '$tableFooterPaddingTopBottom $tableFooterPaddingLeftRight',
        },
      },
      Timeline: {
        timelineTextColor: '#ffffff',
        timelineEventMarkerWidth: 14,
        timelineEventMarkerHeight: 14,
        timelineEventMarkerBorderRadius: 112,
        timelineEventConnectorSize: '1px',
        timelineEventMarkerBorderColor: '#76d961',
        timelineEventMarkerBorderSize: 3.5,
        timelineEventMarkerBorder:
          '$timelineEventMarkerBorderSize solid $timelineEventMarkerBorderColor',
        timelineEventMarkerBackground: '#1c1b22',
        timelineEventColor: '#444444',
        timelineVerticalEventContentPaddingTopBottom: 0,
        timelineVerticalEventContentPaddingLeftRight: 7,
        timelineVerticalEventContentPadding:
          '$timelineVerticalEventContentPaddingTopBottom $timelineVerticalEventContentPaddingLeftRight',
        timelineHorizontalEventContentPaddingTopBottom: 7,
        timelineHorizontalEventContentPaddingLeftRight: 0,
        timelineHorizontalEventContentPadding:
          '$timelineHorizontalEventContentPaddingTopBottom $timelineHorizontalEventContentPaddingLeftRight',
      },
    },
    Media: {
      Carousel: {
        carouselIndicatorsPadding: '1rem',
        carouselIndicatorBg: '#444444',
        carouselIndicatorHoverBg: '#919190',
        carouselIndicatorActiveBg: '#919190',
        carouselIndicatorBorderRadius: '1rem',
        carouselIndicatorWidth: '0.5rem',
        carouselIndicatorHeight: '0.5rem',
      },
      Galleria: {
        Close: {
          galleriaMaskBg: 'rgba(0, 0, 0, 0.4000)',
          galleriaCloseIconMargin: 7,
          galleriaCloseIconFontSize: 28,
          galleriaCloseIconBg: 'rgba(0, 0, 0, 0.0001)',
          galleriaCloseIconColor: 'rgba(255, 255, 255, 0.6000)',
          galleriaCloseIconHoverBg: 'rgba(255, 255, 255, 0.2000)',
          galleriaCloseIconHoverColor: 'rgba(255, 255, 255, 0.8000)',
          galleriaCloseIconWidth: 56,
          galleriaCloseIconHeight: 56,
          galleriaCloseIconBorderRadius: 7,
        },
        Navigator: {
          galleriaItemNavigatorBg: 'rgba(0, 0, 0, 0.0001)',
          galleriaItemNavigatorColor: 'rgba(255, 255, 255, 0.6000)',
          galleriaItemNavigatorMargin: 7,
          galleriaItemNavigatorFontSize: 28,
          galleriaItemNavigatorHoverBg: 'rgba(255, 255, 255, 0.2000)',
          galleriaItemNavigatorHoverColor: 'rgba(255, 255, 255, 0.8000)',
          galleriaItemNavigatorWidth: 56,
          galleriaItemNavigatorHeight: 56,
          galleriaItemNavigatorBorderRadius: 7,
        },
        Caption: {
          galleriaCaptionBg: 'rgba(0, 0, 0, 0.6000)',
          galleriaCaptionTextColor: 'rgba(255, 255, 255, 0.8000)',
          galleriaCaptionPadding: 14,
        },
        Indicators: {
          galleriaIndicatorsPadding: 14,
          galleriaIndicatorBg: 'rgba(255, 255, 255, 0.4000)',
          galleriaIndicatorHoverBg: 'rgba(255, 255, 255, 0.8000)',
          galleriaIndicatorBorderRadius: 14,
          galleriaIndicatorWidth: 7,
          galleriaIndicatorHeight: 7,
          galleriaIndicatorsBgOnItem: 'rgba(0, 0, 0, 0.0001)',
          galleriaIndicatorBgOnItem: 'rgba(255, 255, 255, 0.4000)',
          galleriaIndicatorHoverBgOnItem: 'rgba(255, 255, 255, 0.8000)',
          galleriaIndicatorActiveBgOnItem: 'rgba(255, 255, 255, 0.8000)',
        },
        Thumbnail: {
          galleriaThumbnailContainerBg: '#000000',
          galleriaThumbnailContainerPaddingTopBottom: 7,
          galleriaThumbnailContainerPaddingLeftRight: 7,
          galleriaThumbnailContainerPadding:
            '$galleriaThumbnailContainerPaddingTopBottom $galleriaThumbnailContainerPaddingLeftRight',
          galleriaThumbnailNavigatorBg: 'rgba(0, 0, 0, 0.0001)',
          galleriaThumbnailNavigatorColor: 'rgba(255, 255, 255, 0.6000)',
          galleriaThumbnailNavigatorHoverBg: 'rgba(255, 255, 255, 0.2000)',
          galleriaThumbnailNavigatorHoverColor: 'rgba(255, 255, 255, 0.8000)',
          galleriaThumbnailNavigatorBorderRadius: 7,
          galleriaThumbnailNavigatorWidth: 28,
          galleriaThumbnailNavigatorHeight: 28,
        },
      },
    },
  },
};
