export default {
  list: {
    padding: '{spacing.1}',
    gap: {
      sm: '{spacing.1}',
      md: '{spacing.2}',
    },
    header: {
      padding: '{spacing.4} {spacing.4} 0 {spacing.4}',
    },
    option: {
      padding: '{spacing.2} {spacing.3}',
      borderRadius: '{borderRadius.sm}',
    },
    optionGroup: {
      padding: '{spacing.2} {spacing.3}',
      fontWeight: '{fonts.fontWeight.demibold}',
    },
  },
  focusRing: {
    width: '{borderWidth.md}',
    style: 'none',
    color: '{focusRing.extend.success}',
    offset: '0',
  },
  form: {
    padding: {
      tn: '{spacing.1}',
      xs: '{spacing.2}',
      sm: '{spacing.3}',
      md: '{spacing.4}',
      lg: '{spacing.5}',
      xlg: '{spacing.6}',
      '2xlg': '{spacing.7}',
    },
    borderRadius: {
      sm: '{borderRadius.sm}',
      md: '{borderRadius.md}',
      max: '{borderRadius.max}',
    },
    borderWidth: '{borderWidth.xs}',
    transitionDuration: '{transition.duration.200}',
    size: {
      tn: '{sizing.0pt3}',
      xs: '{sizing.1}',
      sm: '{sizing.2}',
      md: '{sizing.3}',
      lg: '{sizing.4}',
      xlg: '{sizing.5}',
      '2xlg': '{sizing.6}',
      '3xlg': '{sizing.8}',
      '4xlg': '{sizing.10}',
      '5xlg': '{sizing.12}',
      '6xlg': '{sizing.16}',
      '7xlg': '{sizing.20}',
    },
    icon: {
      sm: '{sizing.3}',
      md: '{sizing.4}',
      lg: '{sizing.5}',
      xlg: '{sizing.6}',
    },
    width: {
      xs: '{sizing.6}',
      sm: '{sizing.8}',
      md: '{sizing.10}',
      lg: '{sizing.12}',
      '10xlg': '{sizing.60}',
      full: '{sizing.max}',
    },
    gap: {
      tn: '{spacing.1}',
      xs: '{spacing.2}',
      sm: '{spacing.3}',
      md: '{spacing.4}',
    },
    focusRing: {
      width: '{focusRing.width}',
      style: '{focusRing.style}',
      color: '{focusRing.color}',
      offset: '{focusRing.offset}',
    },
  },
  content: {
    borderRadius: '{borderRadius.md}',
    padding: {
      tn: '{spacing.1}',
      xs: '{spacing.2}',
      sm: '{spacing.4}',
      md: '{spacing.6}',
      lg: '{spacing.7}',
    },
    borderWidth: '{sizing.0pt3}',
    gap: {
      xs: '{spacing.1}',
      sm: '{spacing.2}',
      md: '{spacing.3}',
      lg: '{spacing.4}',
    },
  },
  navigation: {
    width: {
      xs: '{borderWidth.xs}',
      sm: '{borderWidth.md}',
    },
    borderRadius: '{borderRadius.xs}',
    size: {
      tn: '{sizing.1}',
      xs: '{sizing.2}',
      xsm: '{sizing.5}',
      sm: '{sizing.8}',
      md: '{sizing.16}',
    },
    padding: {
      '2xs': '{spacing.1}',
      xs: '{spacing.3}',
      sm: '{spacing.4}',
    },
    submenu: {
      padding: '{spacing.5}',
    },
    list: {
      padding: {
        sm: '{spacing.1}',
        md: '{spacing.2}',
      },
      gap: '{spacing.1}',
    },
    item: {
      padding: '{spacing.2} {spacing.3}',
      borderRadius: '{borderRadius.sm}',
      gap: '{spacing.2}',
    },
    submenuLabel: {
      padding: '{spacing.2} {spacing.3}',
      fontWeight: '{fonts.fontWeight.demibold}',
    },
    submenuIcon: {
      size: '{fonts.fontSize.xl}',
    },
  },
  overlay: {
    mask: {
      transitionDuration: '{transition.duration.200}',
    },
    transitionDuration: '{transition.duration.200}',
    select: {
      borderRadius: '{borderRadius.md}',
      padding: '{spacing.1}',
    },
    borderWidth: '{borderWidth.xs}',
    icon: {
      size: {
        sm: '{sizing.4}',
        md: '{sizing.6}',
        lg: '{sizing.7}',
        xlg: '{sizing.8}',
        '2xlg': '{sizing.9}',
      },
    },
    popover: {
      borderRadius: '{borderRadius.sm}',
      padding: {
        sm: '{spacing.3}',
        md: '{spacing.5}',
      },
    },
    modal: {
      borderRadius: '{borderRadius.xl}',
      padding: {
        xs: '{spacing.4}',
        sm: '{spacing.5}',
        md: '{spacing.6}',
      },
    },
    drawer: {
      width: '{sizing.100}',
      padding: '{spacing.2}',
    },
    gap: {
      xs: '{spacing.1}',
      sm: '{spacing.2}',
      md: '{spacing.3}',
      lg: '{spacing.4}',
    },
    width: '{sizing.68}',
  },
  feedback: {
    transitionDuration: '{transition.duration.200}',
    width: {
      tn: '{sizing.0pt3}',
      xs: '{sizing.1}',
      sm: '{sizing.2}',
      md: '{sizing.3}',
      lg: '{sizing.4}',
      xlg: '{sizing.5}',
      '2xlg': '{sizing.6}',
      '3xlg': '{sizing.7}',
      '4xlg': '{sizing.8}',
    },
    icon: {
      size: {
        xs: '{sizing.2}',
        sm: '{sizing.4}',
        md: '{sizing.6}',
        lg: '{sizing.7}',
        xlg: '{sizing.8}',
        '2xlg': '{sizing.9}',
      },
    },
    padding: {
      md: '{spacing.2}',
      lg: '{spacing.4}',
    },
    height: {
      sm: '{sizing.2}',
      md: '{sizing.3}',
      lg: '{sizing.4}',
      xlg: '{sizing.5}',
      '2xlg': '{sizing.6}',
      '3xlg': '{sizing.7}',
      '4xlg': '{sizing.8}',
      '5xlg': '{sizing.9}',
      '6xlg': '{sizing.10}',
      '7xlg': '{sizing.11}',
      '8xlg': '{sizing.12}',
    },
    gap: {
      xs: '{spacing.1}',
      sm: '{spacing.2}',
      md: '{spacing.3}',
      lg: '{spacing.4}',
    },
  },
  data: {
    padding: {
      xs: '{spacing.1}',
      sm: '{spacing.2}',
      md: '{spacing.3}',
      lg: '{spacing.4}',
      xlg: '{spacing.5}',
    },
    icon: {
      size: {
        md: '{sizing.4}',
        lg: '{sizing.5}',
        xlg: '{sizing.6}',
        '2xlg': '{sizing.7}',
        '3xlg': '{sizing.8}',
        '4xlg': '{sizing.9}',
        '5xlg': '{sizing.10}',
      },
    },
    transitionDuration: '{transition.duration.200}',
    borderWidth: '{borderWidth.none}',
    borderRadius: '{borderRadius.xs}',
    gap: {
      xs: '{spacing.1}',
      sm: '{spacing.2}',
      md: '{spacing.3}',
    },
    width: {
      tn: '{sizing.0pt3}',
      xs: '{sizing.1}',
      sm: '{sizing.2}',
      '13xlg': '{sizing.20}',
    },
  },
  media: {
    size: {
      tn: '{sizing.1}',
      xs: '{sizing.2}',
      sm: '{sizing.8}',
      md: '{sizing.10}',
      lg: '{sizing.14}',
      xlg: '{sizing.16}',
    },
    borderRadius: {
      xs: '{borderRadius.sm}',
      sm: '{borderRadius.md}',
      md: '{borderRadius.lg}',
      lg: '{borderRadius.xl}',
    },
    icon: {
      size: {
        sm: '{sizing.4}',
        md: '{sizing.6}',
        lg: '{sizing.8}',
      },
    },
    transitionDuration: '{transition.duration.200}',
    padding: {
      xs: '{spacing.1}',
      sm: '{spacing.2}',
      md: '{spacing.3}',
      lg: '{spacing.4}',
      '2xlg': '{spacing.5}',
      '3xlg': '{spacing.6}',
    },
    gap: {
      xs: '{spacing.1}',
      sm: '{spacing.2}',
    },
  },
  controls: {
    iconOnly: {
      tn: '{sizing.2}',
      xs: '{sizing.4}',
      sm: '{sizing.5}',
      md: '{sizing.6}',
      lg: '{sizing.7}',
      xlg: '{sizing.8}',
      '2xlg': '{sizing.10}',
      '3xlg': '{sizing.11}',
      '4xlg': '{sizing.14}',
      '5xlg': '{sizing.16}',
    },
    borderRadius: {
      sm: '{borderRadius.md}',
      md: '{borderRadius.lg}',
      max: '{borderRadius.max}',
    },
    gap: {
      sm: '{spacing.2}',
      md: '{spacing.3}',
      lg: '{spacing.4}',
    },
    transitionDuration: '{transition.duration.200}',
    padding: {
      xs: '{spacing.1}',
      sm: '{spacing.2}',
      md: '{spacing.3}',
      lg: '{spacing.4}',
      xlg: '{spacing.5}',
      '2xlg': '{spacing.6}',
    },
    width: {
      tn: '{sizing.0pt3}',
    },
  },
  colorScheme: {
    light: {
      success: {
        '50': '{colors.solid.green.50}',
        '100': '{colors.solid.green.100}',
        '200': '{colors.solid.green.200}',
        '300': '{colors.solid.green.300}',
        '400': '{colors.solid.green.400}',
        '500': '{colors.solid.green.500}',
        '600': '{colors.solid.green.600}',
        '700': '{colors.solid.green.700}',
        '800': '{colors.solid.green.800}',
        '900': '{colors.solid.green.900}',
        '950': '{colors.solid.green.950}',
      },
      info: {
        '50': '{colors.solid.blue.50}',
        '100': '{colors.solid.blue.100}',
        '200': '{colors.solid.blue.200}',
        '300': '{colors.solid.blue.300}',
        '400': '{colors.solid.blue.400}',
        '500': '{colors.solid.blue.500}',
        '600': '{colors.solid.blue.600}',
        '700': '{colors.solid.blue.700}',
        '800': '{colors.solid.blue.800}',
        '900': '{colors.solid.blue.900}',
        '950': '{colors.solid.blue.950}',
      },
      warn: {
        '50': '{colors.solid.yellow.50}',
        '100': '{colors.solid.yellow.100}',
        '200': '{colors.solid.yellow.200}',
        '300': '{colors.solid.yellow.300}',
        '400': '{colors.solid.yellow.400}',
        '500': '{colors.solid.yellow.500}',
        '600': '{colors.solid.yellow.600}',
        '700': '{colors.solid.yellow.700}',
        '800': '{colors.solid.yellow.800}',
        '900': '{colors.solid.yellow.900}',
        '950': '{colors.solid.yellow.950}',
      },
      transparent: 'rgba(255, 255, 255, 0.0001)',
      help: {
        '50': '{colors.solid.purple.50}',
        '100': '{colors.solid.purple.100}',
        '200': '{colors.solid.purple.200}',
        '300': '{colors.solid.purple.300}',
        '400': '{colors.solid.purple.400}',
        '500': '{colors.solid.purple.500}',
        '600': '{colors.solid.purple.600}',
        '700': '{colors.solid.purple.700}',
        '800': '{colors.solid.purple.800}',
        '900': '{colors.solid.purple.900}',
        '950': '{colors.solid.purple.950}',
      },
      error: {
        '50': '{colors.solid.red.50}',
        '100': '{colors.solid.red.100}',
        '200': '{colors.solid.red.200}',
        '300': '{colors.solid.red.300}',
        '400': '{colors.solid.red.400}',
        '500': '{colors.solid.red.500}',
        '600': '{colors.solid.red.600}',
        '700': '{colors.solid.red.700}',
        '800': '{colors.solid.red.800}',
        '900': '{colors.solid.red.900}',
        '950': '{colors.solid.red.950}',
      },
      surface: {
        '0': '{colors.alpha.white.100}',
        '50': '{colors.solid.zinc.50}',
        '100': '{colors.solid.zinc.100}',
        '200': '{colors.solid.zinc.200}',
        '300': '{colors.solid.zinc.300}',
        '400': '{colors.solid.zinc.400}',
        '500': '{colors.solid.zinc.500}',
        '600': '{colors.solid.zinc.600}',
        '700': '{colors.solid.zinc.700}',
        '800': '{colors.solid.zinc.800}',
        '900': '{colors.solid.zinc.900}',
        '950': '{colors.solid.zinc.950}',
      },
      primary: {
        color: '{colors.solid.green.500}',
        contrastColor: '{colors.alpha.white.100}',
        hoverColor: '{colors.solid.green.600}',
        activeColor: '{colors.solid.green.700}',
        hoverBackground: '{colors.solid.green.50}',
        activeBackground: '{colors.solid.green.100}',
        borderColor: '{colors.solid.green.200}',
        selectedBackground: '{colors.solid.green.500}',
        selectedHoverBackground: '{colors.solid.green.600}',
      },
      highlight: {
        background: '{colors.solid.zinc.900}',
        focusBackground: '{colors.solid.zinc.800}',
        color: '{colors.alpha.white.100}',
        focusColor: '{colors.alpha.white.100}',
      },
      focusRing: {
        shadow: '{shadows.xs}',
        extend: {
          invalid: '{colors.solid.red.200}',
          success: '{colors.solid.green.200}',
          warning: '{colors.solid.yellow.200}',
          info: '{colors.solid.blue.200}',
        },
      },
      mask: {
        background: '{colors.alpha.black.40}',
        color: '{surface.200}',
      },
      form: {
        background: '{colors.alpha.white.100}',
        disabledBackground: '{colors.solid.zinc.200}',
        readonlyBackground: '{colors.solid.zinc.100}',
        filledBackground: '{colors.alpha.white.100}',
        filledHoverBackground: '{colors.alpha.white.100}',
        filledFocusBackground: '{colors.alpha.white.100}',
        borderColor: '{colors.solid.zinc.300}',
        hoverBorderPrimaryColor: '{colors.solid.zinc.900}',
        focusBorderPrimaryColor: '{colors.solid.zinc.900}',
        hoverBorderSecondaryColor: '{colors.solid.green.600}',
        focusBorderSecondaryColor: '{colors.solid.green.600}',
        invalidBorderColor: '{colors.solid.red.400}',
        color: '{colors.solid.zinc.950}',
        disabledColor: '{colors.solid.zinc.500}',
        placeholderColor: '{colors.solid.zinc.500}',
        invalidPlaceholderColor: '{colors.solid.red.600}',
        floatLabelColor: '{colors.solid.zinc.500}',
        floatLabelFocusColor: '{colors.solid.zinc.500}',
        floatLabelActiveColor: '{colors.solid.zinc.500}',
        floatLabelInvalidColor: '{form.invalidPlaceholderColor}',
        iconColor: '{colors.solid.zinc.950}',
        backgroundHandler: '{colors.alpha.white.100}',
        shadow: '{shadows.xs}',
      },
      text: {
        color: '{colors.solid.zinc.900}',
        extend: {
          colorPrimaryStatic: '{colors.solid.zinc.900}',
          colorSecondaryStatic: '{colors.alpha.white.100}',
          colorInverted: '{colors.alpha.white.100}',
        },
        hoverColor: '{colors.solid.zinc.700}',
        primaryColor: '{colors.solid.green.600}',
        hoverPrimaryColor: '{colors.solid.green.700}',
        secondaryColor: '{colors.solid.zinc.600}',
        hoverSecondaryColor: '{colors.solid.zinc.400}',
        mutedColor: '{colors.solid.zinc.500}',
        hoverMutedColor: '{colors.solid.zinc.300}',
        disabledColor: '{colors.solid.zinc.300}',
        infoColor: '{info.600}',
        successColor: '{success.700}',
        dangerColor: '{error.600}',
        warningColor: '{warn.600}',
        helpColor: '{help.600}',
      },
      content: {
        background: '{colors.alpha.white.100}',
        hoverBackground: '{colors.solid.zinc.100}',
        borderColor: '{colors.solid.zinc.200}',
        activeBorderColor: '{colors.solid.zinc.800}',
        color: '{text.color}',
        hoverColor: '{text.hoverColor}',
        shadow: '{shadows.md}',
      },
      overlay: {
        select: {
          background: '{colors.alpha.white.100}',
          borderColor: '{colors.solid.zinc.200}',
          color: '{text.color}',
          shadow: '{shadows.md}',
        },
        popover: {
          background: '{colors.alpha.white.100}',
          borderColor: '{form.borderColor}',
          color: '{text.color}',
          shadow: '{shadows.md}',
        },
        modal: {
          background: '{colors.alpha.white.100}',
          borderColor: '{colors.solid.zinc.200}',
          color: '{text.color}',
          shadow: '{shadows.xs}',
        },
      },
      list: {
        option: {
          background: '{colors.alpha.white.100}',
          focusBackground: '{colors.solid.zinc.100}',
          selectedBackground: '{colors.solid.zinc.900}',
          selectedFocusBackground: '{colors.solid.zinc.700}',
          color: '{text.color}',
          focusColor: '{text.color}',
          selectedColor: '{text.extend.colorInverted}',
          selectedFocusColor: '{text.extend.colorInverted}',
          icon: {
            color: '{text.color}',
            focusColor: '{text.color}',
          },
        },
        optionGroup: {
          background: '{colors.alpha.white.100}',
          color: '{text.mutedColor}',
        },
      },
      navigation: {
        submenuLabel: {
          background: 'rgba(255, 255, 255, 0.0000)',
          color: '{text.mutedColor}',
        },
        submenuIcon: {
          color: '{colors.solid.zinc.900}',
          focusColor: '{colors.solid.zinc.900}',
          activeColor: '{colors.alpha.white.100}',
        },
        item: {
          focusBackground: '{colors.solid.zinc.100}',
          activeBackground: '{colors.solid.zinc.900}',
          color: '{colors.solid.zinc.900}',
          focusColor: '{colors.solid.zinc.900}',
          activeColor: '{colors.alpha.white.100}',
          icon: {
            color: '{colors.solid.zinc.900}',
            focusColor: '{colors.solid.zinc.900}',
            activeColor: '{colors.alpha.white.100}',
          },
        },
        shadow: '{shadows.md}',
      },
    },
    dark: {
      success: {
        '50': '{colors.solid.green.950}',
        '100': '{colors.solid.green.900}',
        '200': '{colors.solid.green.800}',
        '300': '{colors.solid.green.700}',
        '400': '{colors.solid.green.600}',
        '500': '{colors.solid.green.500}',
        '600': '{colors.solid.green.400}',
        '700': '{colors.solid.green.300}',
        '800': '{colors.solid.green.200}',
        '900': '{colors.solid.green.100}',
        '950': '{colors.solid.green.50}',
      },
      info: {
        '50': '{colors.solid.blue.950}',
        '100': '{colors.solid.blue.900}',
        '200': '{colors.solid.blue.800}',
        '300': '{colors.solid.blue.700}',
        '400': '{colors.solid.blue.600}',
        '500': '{colors.solid.blue.500}',
        '600': '{colors.solid.blue.400}',
        '700': '{colors.solid.blue.300}',
        '800': '{colors.solid.blue.200}',
        '900': '{colors.solid.blue.100}',
        '950': '{colors.solid.blue.50}',
      },
      warn: {
        '50': '{colors.solid.yellow.950}',
        '100': '{colors.solid.yellow.900}',
        '200': '{colors.solid.yellow.800}',
        '300': '{colors.solid.yellow.700}',
        '400': '{colors.solid.yellow.600}',
        '500': '{colors.solid.yellow.500}',
        '600': '{colors.solid.yellow.400}',
        '700': '{colors.solid.yellow.300}',
        '800': '{colors.solid.yellow.200}',
        '900': '{colors.solid.yellow.100}',
        '950': '{colors.solid.yellow.50}',
      },
      transparent: 'rgba(0, 0, 0, 0.0001)',
      help: {
        '50': '{colors.solid.purple.950}',
        '100': '{colors.solid.purple.900}',
        '200': '{colors.solid.purple.800}',
        '300': '{colors.solid.purple.700}',
        '400': '{colors.solid.purple.600}',
        '500': '{colors.solid.purple.500}',
        '600': '{colors.solid.purple.400}',
        '700': '{colors.solid.purple.300}',
        '800': '{colors.solid.purple.200}',
        '900': '{colors.solid.purple.100}',
        '950': '{colors.solid.purple.50}',
      },
      error: {
        '50': '{colors.solid.red.950}',
        '100': '{colors.solid.red.900}',
        '200': '{colors.solid.red.800}',
        '300': '{colors.solid.red.700}',
        '400': '{colors.solid.red.600}',
        '500': '{colors.solid.red.500}',
        '600': '{colors.solid.red.400}',
        '700': '{colors.solid.red.300}',
        '800': '{colors.solid.red.200}',
        '900': '{colors.solid.red.100}',
        '950': '{colors.solid.red.50}',
      },
      surface: {
        '0': '{colors.alpha.black.100}',
        '50': '{colors.solid.zinc.950}',
        '100': '{colors.solid.zinc.900}',
        '200': '{colors.solid.zinc.800}',
        '300': '{colors.solid.zinc.700}',
        '400': '{colors.solid.zinc.600}',
        '500': '{colors.solid.zinc.500}',
        '600': '{colors.solid.zinc.400}',
        '700': '{colors.solid.zinc.300}',
        '800': '{colors.solid.zinc.200}',
        '900': '{colors.solid.zinc.100}',
        '950': '{colors.solid.zinc.50}',
      },
      primary: {
        color: '{colors.solid.green.500}',
        contrastColor: '{colors.solid.zinc.900}',
        hoverColor: '{colors.solid.green.400}',
        activeColor: '{colors.solid.green.300}',
        hoverBackground: '{colors.solid.green.950}',
        activeBackground: '{colors.solid.green.900}',
        borderColor: '{colors.solid.green.800}',
        selectedBackground: '{colors.solid.green.500}',
        selectedHoverBackground: '{colors.solid.green.600}',
      },
      highlight: {
        background: '{colors.solid.zinc.100}',
        focusBackground: '{colors.solid.zinc.200}',
        color: '{colors.solid.zinc.900}',
        focusColor: '{colors.solid.zinc.900}',
      },
      focusRing: {
        shadow: '{shadows.xs}',
        extend: {
          invalid: '{colors.solid.red.800}',
          success: '{colors.solid.green.800}',
          warning: '{colors.solid.yellow.800}',
          info: '{colors.solid.blue.800}',
        },
      },
      mask: {
        background: '{colors.alpha.black.60}',
        color: '{surface.800}',
      },
      form: {
        background: '{colors.solid.zinc.950}',
        disabledBackground: '{colors.solid.zinc.800}',
        readonlyBackground: '{colors.solid.zinc.900}',
        filledBackground: '{colors.solid.zinc.950}',
        filledHoverBackground: '{colors.solid.zinc.950}',
        filledFocusBackground: '{colors.solid.zinc.950}',
        borderColor: '{colors.solid.zinc.700}',
        hoverBorderPrimaryColor: '{colors.solid.zinc.100}',
        focusBorderPrimaryColor: '{colors.solid.zinc.100}',
        hoverBorderSecondaryColor: '{colors.solid.green.400}',
        focusBorderSecondaryColor: '{colors.solid.green.400}',
        invalidBorderColor: '{colors.solid.red.600}',
        color: '{colors.alpha.white.100}',
        disabledColor: '{colors.solid.zinc.500}',
        placeholderColor: '{colors.solid.zinc.500}',
        invalidPlaceholderColor: '{colors.solid.red.400}',
        floatLabelColor: '{colors.solid.zinc.500}',
        floatLabelFocusColor: '{colors.solid.zinc.500}',
        floatLabelActiveColor: '{colors.solid.zinc.500}',
        floatLabelInvalidColor: '{form.invalidPlaceholderColor}',
        iconColor: '{colors.alpha.white.100}',
        backgroundHandler: '{colors.alpha.white.100}',
        shadow: '{shadows.xs}',
      },
      text: {
        color: '{colors.alpha.white.100}',
        extend: {
          colorPrimaryStatic: '{colors.solid.zinc.900}',
          colorSecondaryStatic: '{colors.alpha.white.100}',
          colorInverted: '{colors.solid.zinc.900}',
        },
        hoverColor: '{colors.solid.zinc.300}',
        primaryColor: '{colors.solid.green.400}',
        hoverPrimaryColor: '{colors.solid.green.300}',
        secondaryColor: '{colors.solid.zinc.400}',
        hoverSecondaryColor: '{colors.solid.zinc.600}',
        mutedColor: '{colors.solid.zinc.500}',
        hoverMutedColor: '{colors.solid.zinc.700}',
        disabledColor: '{colors.solid.zinc.700}',
        infoColor: '{info.400}',
        successColor: '{success.300}',
        dangerColor: '{error.400}',
        warningColor: '{warn.400}',
        helpColor: '{help.400}',
      },
      content: {
        background: '{colors.solid.zinc.900}',
        hoverBackground: '{colors.solid.zinc.800}',
        borderColor: '{colors.solid.zinc.800}',
        activeBorderColor: '{colors.solid.zinc.200}',
        color: '{text.color}',
        hoverColor: '{text.hoverColor}',
        shadow: '{shadows.md}',
      },
      overlay: {
        select: {
          background: '{colors.solid.zinc.900}',
          borderColor: '{colors.solid.zinc.800}',
          color: '{text.color}',
          shadow: '{shadows.md}',
        },
        popover: {
          background: '{colors.solid.zinc.900}',
          borderColor: '{form.borderColor}',
          color: '{text.color}',
          shadow: '{shadows.md}',
        },
        modal: {
          background: '{colors.solid.zinc.900}',
          borderColor: '{colors.solid.zinc.800}',
          color: '{text.color}',
          shadow: '{shadows.xs}',
        },
      },
      list: {
        option: {
          background: '{colors.solid.zinc.900}',
          focusBackground: '{colors.solid.zinc.800}',
          selectedBackground: '{colors.solid.zinc.100}',
          selectedFocusBackground: '{colors.solid.zinc.300}',
          color: '{text.color}',
          focusColor: '{text.color}',
          selectedColor: '{text.extend.colorInverted}',
          selectedFocusColor: '{text.extend.colorInverted}',
          icon: {
            color: '{text.color}',
            focusColor: '{text.color}',
          },
        },
        surface: '#ffffff',
        optionGroup: {
          background: '{colors.solid.zinc.900}',
          color: '{text.mutedColor}',
        },
      },
      navigation: {
        submenuLabel: {
          background: 'rgba(255, 255, 255, 0.0000)',
          color: '{text.mutedColor}',
        },
        submenuIcon: {
          color: '{colors.solid.zinc.100}',
          focusColor: '{colors.solid.zinc.100}',
          activeColor: '{colors.solid.zinc.900}',
        },
        item: {
          focusBackground: '{colors.solid.zinc.900}',
          activeBackground: '{colors.solid.zinc.100}',
          color: '{colors.alpha.white.100}',
          focusColor: '{colors.alpha.white.100}',
          activeColor: '{colors.solid.zinc.900}',
          icon: {
            color: '{colors.alpha.white.100}',
            focusColor: '{colors.alpha.white.100}',
            activeColor: '{colors.solid.zinc.900}',
          },
        },
        shadow: '{shadows.md}',
      },
    },
  },
  sizing: {
    form: {
      root: {
        fontSize: '{fonts.fontSize.base}',
        paddingX: '{spacing.4}',
        paddingY: '{spacing.4}',
      },
      sm: {
        fontSize: '{fonts.fontSize.base}',
        paddingX: '{spacing.3}',
        paddingY: '{spacing.3}',
      },
      lg: {
        fontSize: '{fonts.fontSize.base}',
        paddingX: '{spacing.5}',
        paddingY: '{spacing.5}',
      },
      xlg: {
        fontSize: '{fonts.fontSize.base}',
        paddingX: '{spacing.6}',
        paddingY: '{spacing.6}',
      },
    },
    overlay: {
      root: {
        width: '{sizing.100}',
      },
      sm: {
        width: '{sizing.80}',
      },
      lg: {
        width: '{sizing.120}',
      },
      xlg: {
        width: '{sizing.128}',
      },
    },
    messages: {
      root: {
        width: '{sizing.100}',
      },
      sm: {
        width: '{sizing.80}',
      },
      lg: {
        width: '{sizing.120}',
      },
      xlg: {
        width: '{sizing.128}',
      },
    },
  },
};
