export default {
  list: {
    padding: '0.25rem',
    gap: '0.25rem',
    header: {
      padding: '0.625rem 1rem 0 1rem',
    },
    option: {
      padding: '0.5rem 0.75rem',
      borderRadius: '0.5rem',
    },
    optionGroup: {
      padding: '0.5rem 0.75rem',
      fontWeight: '600',
    },
  },
  focusRing: {
    width: '0.25rem',
    style: 'none',
    color: '#ffffff',
    offset: '0',
    shadow: '0 0 0 0.25rem {primary.200}',
  },
  primary: {
    '50': '{primitive.colors.green.50}',
    '100': '{primitive.colors.green.100}',
    '200': '{primitive.colors.green.200}',
    '300': '{primitive.colors.green.300}',
    '400': '{primitive.colors.green.400}',
    '500': '{primitive.colors.green.500}',
    '600': '{primitive.colors.green.600}',
    '700': '{primitive.colors.green.700}',
    '800': '{primitive.colors.green.800}',
    '900': '{primitive.colors.green.900}',
    '950': '{primitive.colors.green.950}',
  },
  formField: {
    paddingX: '0.75rem',
    paddingY: '0.75rem',
    borderRadius: '{primitive.borderRadius.md}',
    transitionDuration: '{transitionDuration}',
    sm: {
      fontSize: '0.0625rem',
      paddingX: '0.0446rem',
      paddingY: '0.0357rem',
    },
    lg: {
      fontSize: '0.0804rem',
      paddingX: '0.0625rem',
      paddingY: '0.0536rem',
    },
    focusRing: {
      width: '{focusRing.width}',
      style: '{focusRing.style}',
      color: '{focusRing.color}',
      offset: '{focusRing.offset}',
      shadow: '{focusRing.shadow}',
    },
  },
  content: {
    borderRadius: '{primitive.borderRadius.md}',
  },
  mask: {
    transitionDuration: '0.15000000596046448ms',
  },
  navigation: {
    list: {
      padding: '0.5rem 0',
      gap: '0.25rem',
    },
    item: {
      padding: '0.625rem 1rem',
      borderRadius: '0rem',
      gap: '0.5rem',
    },
    submenuLabel: {
      padding: '0.625rem 1rem',
      fontWeight: '600',
    },
    submenuIcon: {
      size: '0.0625rem',
    },
  },
  overlay: {
    select: {
      borderRadius: '{primitive.borderRadius.md}',
      shadow: '0 3.5px 7px 0 rgba(0, 0, 0, 0.2)',
    },
    popover: {
      borderRadius: '{primitive.borderRadius.md}',
      padding: '0.75rem',
      shadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
    },
    modal: {
      borderRadius: '{primitive.borderRadius.xl}',
      padding: '1.5rem',
      shadow: '0 1px 3px rgba(0, 0, 0, 0.3)',
    },
    navigation: {
      shadow: '0 2px 12px 0 rgba(0, 0, 0, 0.1)',
    },
  },
  transitionDuration: '0.20000000298023224ms',
  disabledOpacity: '50',
  iconSizeMedium: '1rem',
  iconSizeLarge: '1.25rem',
  anchorGutter: '0.1429rem',
  colorScheme: {
    light: {
      extend: {
        pallete: {
          success: {
            '50': '{primitive.colors.green.50}',
            '100': '{primitive.colors.green.100}',
            '200': '{primitive.colors.green.200}',
            '300': '{primitive.colors.green.300}',
            '400': '{primitive.colors.green.400}',
            '500': '{primitive.colors.green.500}',
            '600': '{primitive.colors.green.600}',
            '700': '{primitive.colors.green.700}',
            '800': '{primitive.colors.green.800}',
            '900': '{primitive.colors.green.900}',
            '950': '{primitive.colors.green.950}',
          },
          info: {
            '50': '{primitive.colors.blue.50}',
            '100': '{primitive.colors.blue.100}',
            '200': '{primitive.colors.blue.200}',
            '300': '{primitive.colors.blue.300}',
            '400': '{primitive.colors.blue.400}',
            '500': '{primitive.colors.blue.500}',
            '600': '{primitive.colors.blue.600}',
            '700': '{primitive.colors.blue.700}',
            '800': '{primitive.colors.blue.800}',
            '900': '{primitive.colors.blue.900}',
            '950': '{primitive.colors.blue.950}',
          },
          warn: {
            '50': '{primitive.colors.yellow.50}',
            '100': '{primitive.colors.yellow.100}',
            '200': '{primitive.colors.yellow.200}',
            '300': '{primitive.colors.yellow.300}',
            '400': '{primitive.colors.yellow.400}',
            '500': '{primitive.colors.yellow.500}',
            '600': '{primitive.colors.yellow.600}',
            '700': '{primitive.colors.yellow.700}',
            '800': '{primitive.colors.yellow.800}',
            '900': '{primitive.colors.yellow.900}',
            '950': '{primitive.colors.yellow.950}',
          },
          help: {
            '50': '{primitive.colors.purple.50}',
            '100': '{primitive.colors.purple.100}',
            '200': '{primitive.colors.purple.200}',
            '300': '{primitive.colors.purple.300}',
            '400': '{primitive.colors.purple.400}',
            '500': '{primitive.colors.purple.500}',
            '600': '{primitive.colors.purple.600}',
            '700': '{primitive.colors.purple.700}',
            '800': '{primitive.colors.purple.800}',
            '900': '{primitive.colors.purple.900}',
            '950': '{primitive.colors.purple.950}',
          },
          danger: {
            '50': '{primitive.colors.red.50}',
            '100': '{primitive.colors.red.100}',
            '200': '{primitive.colors.red.200}',
            '300': '{primitive.colors.red.300}',
            '400': '{primitive.colors.red.400}',
            '500': '{primitive.colors.red.500}',
            '600': '{primitive.colors.red.600}',
            '700': '{primitive.colors.red.700}',
            '800': '{primitive.colors.red.800}',
            '900': '{primitive.colors.red.900}',
            '950': '{primitive.colors.red.950}',
          },
        },
      },
      surface: {
        '0': '#ffffff',
        '50': '{primitive.colors.zinc.50}',
        '100': '{primitive.colors.zinc.100}',
        '200': '{primitive.colors.zinc.200}',
        '300': '{primitive.colors.zinc.300}',
        '400': '{primitive.colors.zinc.400}',
        '500': '{primitive.colors.zinc.500}',
        '600': '{primitive.colors.zinc.600}',
        '700': '{primitive.colors.zinc.700}',
        '800': '{primitive.colors.zinc.800}',
        '900': '{primitive.colors.zinc.900}',
        '950': '{primitive.colors.zinc.950}',
        extend: {
          transparent: 'rgba(255, 255, 255, 0.0001)',
        },
      },
      primary: {
        color: '{semantic.primary.500}',
        contrastColor: '{surface.0}',
        hoverColor: '{semantic.primary.600}',
        activeColor: '{semantic.primary.700}',
      },
      highlight: {
        background: '{primitive.colors.zinc.900}',
        focusBackground: '{primitive.colors.zinc.800}',
        color: '{primitive.extend.white.100}',
        focusColor: '{primitive.extend.white.100}',
      },
      focusRing: {
        shadow: '0 0 0 0.2rem {primary.200}',
        extend: {
          invalid: '{primitive.colors.red.200}',
          success: '{primitive.colors.green.200}',
          warning: '{primitive.colors.yellow.200}',
          info: '{primitive.colors.blue.200}',
        },
      },
      mask: {
        background: 'rgba(0, 0, 0, 0.4000)',
        color: '{surface.200}',
      },
      formField: {
        background: '{primitive.extend.white.100}',
        disabledBackground: '{primitive.colors.zinc.200}',
        readonlyBackground: '{primitive.colors.zinc.100}',
        filledBackground: '{primitive.extend.white.100}',
        filledHoverBackground: '{primitive.extend.white.100}',
        filledFocusBackground: '{primitive.extend.white.100}',
        borderColor: '{primitive.colors.zinc.300}',
        hoverBorderPrimaryColor: '{primitive.colors.zinc.900}',
        focusBorderPrimaryColor: '{primitive.colors.zinc.900}',
        hoverBorderSecondaryColor: '{primitive.colors.green.600}',
        focusBorderSecondaryColor: '{primitive.colors.green.600}',
        invalidBorderColor: '{primitive.colors.red.400}',
        color: '{primitive.colors.zinc.950}',
        disabledColor: '{primitive.colors.zinc.500}',
        placeholderColor: '{primitive.colors.zinc.500}',
        invalidPlaceholderColor: '{primitive.colors.red.600}',
        floatLabelColor: '{primitive.colors.zinc.500}',
        floatLabelFocusColor: '{primitive.colors.zinc.500}',
        floatLabelActiveColor: '{primitive.colors.zinc.500}',
        floatLabelInvalidColor: '{formField.invalidPlaceholderColor}',
        iconColor: '{primitive.colors.zinc.950}',
        shadow: 'rgba(0, 0, 0, 0.0000)',
        backgroundHandler: '{primitive.extend.white.100}',
      },
      text: {
        color: '{primitive.colors.zinc.900}',
        extend: {
          colorPrimaryStatic: '{primitive.colors.zinc.900}',
          colorSecondaryStatic: '{primitive.extend.white.100}',
          colorInverted: '{primitive.extend.white.100}',
        },
        hoverColor: '{primitive.colors.zinc.700}',
        mutedColor: '{primitive.colors.zinc.500}',
        hoverMutedColor: '{primitive.colors.zinc.300}',
      },
      content: {
        background: '{primitive.extend.white.100}',
        hoverBackground: '{primitive.colors.zinc.100}',
        borderColor: '{primitive.colors.zinc.200}',
        color: '{text.color}',
        hoverColor: '{text.hoverColor}',
      },
      list: {
        option: {
          background: '{primitive.extend.white.100}',
          focusBackground: '{primitive.colors.zinc.100}',
          selectedBackground: '{primitive.colors.zinc.900}',
          selectedFocusBackground: '{primitive.colors.zinc.700}',
          color: '{text.color}',
          focusColor: '{text.color}',
          selectedColor: '{text.extend.colorInverted}',
          selectedFocusColor: '{text.extend.colorInverted}',
          icon: {
            color: '{text.color}',
            focusColor: '{text.color}',
          },
        },
        surface: '#ffffff',
        optionGroup: {
          background: '{primitive.extend.white.100}',
          color: '{text.mutedColor}',
        },
      },
      overlay: {
        select: {
          background: '{primitive.extend.white.100}',
          borderColor: '{primitive.colors.zinc.200}',
          color: '{text.color}',
        },
        popover: {
          background: '{primitive.extend.white.100}',
          borderColor: '{formField.borderColor}',
          color: '{text.color}',
          shadow: 'rgba(24, 26, 31, 0.2000)',
        },
        modal: {
          background: '{primitive.extend.white.100}',
          borderColor: '{primitive.colors.zinc.200}',
          color: '{text.color}',
        },
      },
      navigation: {
        submenuLabel: {
          background: 'rgba(255, 255, 255, 0.0000)',
          color: '{text.color}',
        },
        submenuIcon: {
          color: '{surface.400}',
          focusColor: '{surface.500}',
          activeColor: '{surface.500}',
        },
        item: {
          focusBackground: '{surface.100}',
          activeBackground: '{surface.100}',
          color: '{text.color}',
          focusColor: '{text.hoverColor}',
          icon: {
            color: '{surface.400}',
            focusColor: '{surface.500}',
            activeColor: '{surface.500}',
          },
          activeColor: '{text.hoverColor}',
        },
      },
    },
    dark: {
      extend: {
        pallete: {
          success: {
            '50': '{primitive.colors.green.950}',
            '100': '{primitive.colors.green.900}',
            '200': '{primitive.colors.green.800}',
            '300': '{primitive.colors.green.700}',
            '400': '{primitive.colors.green.600}',
            '500': '{primitive.colors.green.500}',
            '600': '{primitive.colors.green.400}',
            '700': '{primitive.colors.green.300}',
            '800': '{primitive.colors.green.200}',
            '900': '{primitive.colors.green.100}',
            '950': '{primitive.colors.green.50}',
          },
          info: {
            '50': '{primitive.colors.blue.950}',
            '100': '{primitive.colors.blue.900}',
            '200': '{primitive.colors.blue.800}',
            '300': '{primitive.colors.blue.700}',
            '400': '{primitive.colors.blue.600}',
            '500': '{primitive.colors.blue.500}',
            '600': '{primitive.colors.blue.400}',
            '700': '{primitive.colors.blue.300}',
            '800': '{primitive.colors.blue.200}',
            '900': '{primitive.colors.blue.100}',
            '950': '{primitive.colors.blue.50}',
          },
          warn: {
            '50': '{primitive.colors.yellow.950}',
            '100': '{primitive.colors.yellow.900}',
            '200': '{primitive.colors.yellow.800}',
            '300': '{primitive.colors.yellow.700}',
            '400': '{primitive.colors.yellow.600}',
            '500': '{primitive.colors.yellow.500}',
            '600': '{primitive.colors.yellow.400}',
            '700': '{primitive.colors.yellow.300}',
            '800': '{primitive.colors.yellow.200}',
            '900': '{primitive.colors.yellow.100}',
            '950': '{primitive.colors.yellow.50}',
          },
          help: {
            '50': '{primitive.colors.purple.950}',
            '100': '{primitive.colors.purple.900}',
            '200': '{primitive.colors.purple.800}',
            '300': '{primitive.colors.purple.700}',
            '400': '{primitive.colors.purple.600}',
            '500': '{primitive.colors.purple.500}',
            '600': '{primitive.colors.purple.400}',
            '700': '{primitive.colors.purple.300}',
            '800': '{primitive.colors.purple.200}',
            '900': '{primitive.colors.purple.100}',
            '950': '{primitive.colors.purple.50}',
          },
          danger: {
            '50': '{primitive.colors.red.950}',
            '100': '{primitive.colors.red.900}',
            '200': '{primitive.colors.red.800}',
            '300': '{primitive.colors.red.700}',
            '400': '{primitive.colors.red.600}',
            '500': '{primitive.colors.red.500}',
            '600': '{primitive.colors.red.400}',
            '700': '{primitive.colors.red.300}',
            '800': '{primitive.colors.red.200}',
            '900': '{primitive.colors.red.100}',
            '950': '{primitive.colors.red.50}',
          },
        },
      },
      surface: {
        '0': '#000000',
        '50': '{primitive.colors.zinc.950}',
        '100': '{primitive.colors.zinc.900}',
        '200': '{primitive.colors.zinc.800}',
        '300': '{primitive.colors.zinc.700}',
        '400': '{primitive.colors.zinc.600}',
        '500': '{primitive.colors.zinc.500}',
        '600': '{primitive.colors.zinc.400}',
        '700': '{primitive.colors.zinc.300}',
        '800': '{primitive.colors.zinc.200}',
        '900': '{primitive.colors.zinc.100}',
        '950': '{primitive.colors.zinc.50}',
        extend: {
          transparent: 'rgba(0, 0, 0, 0.0001)',
        },
      },
      primary: {
        color: '{semantic.primary.500}',
        contrastColor: '{primitive.colors.zinc.900}',
        hoverColor: '{semantic.primary.400}',
        activeColor: '{semantic.primary.300}',
      },
      highlight: {
        background: '{primitive.colors.zinc.100}',
        focusBackground: '{primitive.colors.zinc.200}',
        color: '{primitive.colors.zinc.900}',
        focusColor: '{primitive.colors.zinc.900}',
      },
      focusRing: {
        shadow: '0 0 0 0.2rem {primary.800}',
        extend: {
          invalid: '{primitive.colors.red.800}',
          success: '{primitive.colors.green.800}',
          warning: '{primitive.colors.yellow.800}',
          info: '{primitive.colors.blue.800}',
        },
      },
      mask: {
        background: 'rgba(0, 0, 0, 0.4000)',
        color: '{surface.800}',
      },
      formField: {
        background: '{primitive.colors.zinc.950}',
        disabledBackground: '{primitive.colors.zinc.800}',
        readonlyBackground: '{primitive.colors.zinc.900}',
        filledBackground: '{primitive.colors.zinc.950}',
        filledHoverBackground: '{primitive.colors.zinc.950}',
        filledFocusBackground: '{primitive.colors.zinc.950}',
        borderColor: '{primitive.colors.zinc.700}',
        hoverBorderPrimaryColor: '{primitive.colors.zinc.100}',
        focusBorderPrimaryColor: '{primitive.colors.zinc.100}',
        hoverBorderSecondaryColor: '{primitive.colors.green.400}',
        focusBorderSecondaryColor: '{primitive.colors.green.400}',
        invalidBorderColor: '{primitive.colors.red.600}',
        color: '{primitive.extend.white.100}',
        disabledColor: '{primitive.colors.zinc.500}',
        placeholderColor: '{primitive.colors.zinc.500}',
        invalidPlaceholderColor: '{primitive.colors.red.400}',
        floatLabelColor: '{primitive.colors.zinc.500}',
        floatLabelFocusColor: '{primitive.colors.zinc.500}',
        floatLabelActiveColor: '{primitive.colors.zinc.500}',
        floatLabelInvalidColor: '{formField.invalidPlaceholderColor}',
        iconColor: '{primitive.extend.white.100}',
        shadow: 'rgba(255, 255, 255, 0.0000)',
        backgroundHandler: '{primitive.extend.white.100}',
      },
      text: {
        color: '{primitive.extend.white.100}',
        extend: {
          colorPrimaryStatic: '{primitive.colors.zinc.900}',
          colorSecondaryStatic: '{primitive.extend.white.100}',
          colorInverted: '{primitive.colors.zinc.900}',
        },
        hoverColor: '{primitive.colors.zinc.300}',
        mutedColor: '{primitive.colors.zinc.500}',
        hoverMutedColor: '{primitive.colors.zinc.700}',
      },
      content: {
        background: '{primitive.colors.zinc.900}',
        hoverBackground: '{primitive.colors.zinc.800}',
        borderColor: '{primitive.colors.zinc.800}',
        color: '{text.color}',
        hoverColor: '{text.hoverColor}',
      },
      list: {
        option: {
          background: '{primitive.colors.zinc.900}',
          focusBackground: '{primitive.colors.zinc.800}',
          selectedBackground: '{primitive.colors.zinc.100}',
          selectedFocusBackground: '{primitive.colors.zinc.300}',
          color: '{text.color}',
          focusColor: '{text.color}',
          selectedColor: '{text.extend.colorInverted}',
          selectedFocusColor: '{text.extend.colorInverted}',
          icon: {
            color: '{text.color}',
            focusColor: '{text.color}',
          },
        },
        surface: '#ffffff',
        optionGroup: {
          background: '{primitive.colors.zinc.900}',
          color: '{text.mutedColor}',
        },
      },
      overlay: {
        select: {
          background: '{primitive.colors.zinc.900}',
          borderColor: '{primitive.colors.zinc.800}',
          color: '{text.color}',
        },
        popover: {
          background: '{primitive.colors.zinc.900}',
          borderColor: '{formField.borderColor}',
          color: '{text.color}',
          shadow: 'rgba(24, 26, 31, 0.2000)',
        },
        modal: {
          background: '{primitive.colors.zinc.900}',
          borderColor: '{primitive.colors.zinc.800}',
          color: '{text.color}',
        },
      },
      navigation: {
        submenuLabel: {
          background: '#ffffff',
          color: '#ffffff',
        },
        submenuIcon: {
          color: '#ffffff',
          focusColor: '#ffffff',
          activeColor: '#ffffff',
        },
        item: {
          focusBackground: '#ffffff',
          activeBackground: '#ffffff',
          color: '#ffffff',
          focusColor: '#ffffff',
          icon: {
            color: '#ffffff',
            focusColor: '#ffffff',
            activeColor: '#ffffff',
          },
          activeColor: '#ffffff',
        },
      },
    },
  },
};
