name: "Запрос на создание компонента"
description: "Форма для запроса создания новых компонентов дизайн-системы"
title: "[NEW] "
labels: ["type/feature", "status/needs-triage", "area/new-component"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Форма предназначена для сбора структурированной информации о необходимости создания нового компонента в дизайн-системе.
        
        **Перед созданием нового компонента, убедитесь что:**
        - Аналогичный компонент не существует в системе
        - Функциональность нельзя реализовать комбинацией существующих компонентов
        - Компонент будет переиспользован в минимум 3 местах
        
  - type: input
    id: component_title
    attributes:
      label: "Название и назначение компонента"
      description: "Используйте формат: [компонент]:[назначение]"
      placeholder: "Например: ProgressStepper: для отображения многошагового процесса"
    validations:
      required: true
      
  - type: textarea
    id: component_description
    attributes:
      label: "Подробное описание компонента"
      description: "Используйте структуру: [Добавить] → [Результат] → [Причина]"
      placeholder: |
        **[Добавить]:** Что именно предлагается добавить
        
        **[Результат]:** Какой результат ожидается от нового компонента
        
        **[Причина]:** Почему возникла необходимость в новом компоненте
      render: markdown
    validations:
      required: true
      
  - type: input
    id: design_prototype
    attributes:
      label: "Ссылка на дизайн-файл с прототипом"
      description: "Приложите ссылку на прототип нового компонента"
      placeholder: "https://figma.com/file/..."
    validations:
      required: true
      
  - type: textarea
    id: use_cases
    attributes:
      label: "Use Cases и сценарии использования"
      description: "Опишите основные сценарии использования компонента"
      placeholder: |
        **1. Primary Use Case:** Основной сценарий использования
        
        **2. Secondary Use Cases:** Дополнительные сценарии
        
        **3. Edge Cases:** Граничные случаи и особые ситуации
      render: markdown
    validations:
      required: true
      
  - type: checkboxes
    id: frameworks
    attributes:
      label: "Целевые фреймворки"
      description: "Выберите фреймворки, для которых нужен компонент"
      options:
        - label: "React"
          required: false
        - label: "Vue"
          required: false
        - label: "Angular"
          required: false
        - label: "React Native"
          required: false
        - label: "Vanilla JavaScript"
          required: false
          
  - type: dropdown
    id: component_complexity
    attributes:
      label: "Сложность компонента"
      description: "Оцените предполагаемую сложность реализации"
      options:
        - "Simple - базовый UI элемент"
        - "Medium - компонент с состоянием"
        - "Complex - составной компонент с множественной логикой"
        - "Advanced - компонент требующий специальной архитектуры"
    validations:
      required: true
      
  - type: textarea
    id: technical_requirements
    attributes:
      label: "Технические требования"
      description: "Укажите особые технические требования к компоненту"
      placeholder: |
        **Accessibility:** Требования к доступности (WCAG level)
        **Performance:** Особые требования к производительности
        **Browser Support:** Минимальные версии браузеров
        **Dependencies:** Внешние зависимости если нужны
        **API Integration:** Требования к API если applicable
      render: markdown
      
  - type: dropdown
    id: priority
    attributes:
      label: "Приоритет запроса"
      description: "Укажите приоритет создания компонента"
      options:
        - "Critical - блокирует release"
        - "High - нужен в текущем sprint"
        - "Medium - планируется в ближайшие месяцы"
        - "Low - nice to have"
    validations:
      required: true
      
  - type: textarea
    id: similar_components
    attributes:
      label: "Похожие компоненты"
      description: "Укажите похожие компоненты в других дизайн-системах или библиотеках"
      placeholder: |
        **Примеры из других систем:**
        - Material UI: ComponentName
        - Ant Design: ComponentName
        - Chakra UI: ComponentName
        
        **Отличия от существующих решений:**
        - Что будет уникального в нашей реализации
      render: markdown
      
  - type: textarea
    id: additional_context
    attributes:
      label: "Дополнительная информация"
      description: |
        Любая дополнительная информация:
        - Ссылки на research или user feedback
        - Примеры использования в продукте
        - Временные рамки и deadlines
        - Stakeholder requirements
      placeholder: "Укажите дополнительную информацию..."
      render: markdown