name: "Изменение компонента"
description: "Форма для запроса изменений в существующие компоненты дизайн-системы"
title: "[ИЗМЕНЕНИЕ] "
labels: ["type/enhancement", "status/needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Используйте формат: [компонент]:[описание изменения]**
        Например: "Dialog: реализовать возможность изменения размера окна"

        Форма предназначена для сбора информации о необходимости изменения компонента в дизайн-системе.
        **Перед созданием запроса на изменение:**
        - Убедитесь, что изменение не нарушит существующую функциональность
        - Проверьте, не было ли уже создано похожего запроса
        - Подготовьте обоснование необходимости изменения

  - type: input
    id: title
    attributes:
      label: "Заголовок обращения"
      description: "Краткое описание предлагаемого изменения по шаблону {компонент}{изменение}"
      placeholder: "Например: Алерт: добавить возможность закрытия по таймеру"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: "Компонент для изменения"
      description: "Выберите компонент, который требует изменений"
      options:
        - "Menu"
        - "Breadcrumb"
        - "Menubar"
        - "MegaMenu"
        - "TieredMenu"
        - "PanelMenu"
        - "Tab"
        - "DataTable"
        - "Paginator"
        - "Timeline"
        - "Upload"
        - "Carousel"
        - "Galleria"
        - "MenuItem.Base"
        - "MenuItem.Group"
        - "MenuItem.Node"
        - "MenuItem.Template"
        - "Avatar"
        - "Badge"
        - "Chip"
        - "MeterGroup"
        - "ProgressBar"
        - "Tag"
        - "ProgressSpinner"
        - "Skeleton"
        - "Tooltip"
        - "Dialog"
        - "ConfirmDialog"
        - "OverlayPanel"
        - "Sidebar"
        - "Divider"
        - "ScrollPanel"
        - "Accordion"
        - "Card"
        - "Stepper"
        - "Message"
        - "Button"
        - "Button.Badge"
        - "Button.Severity"
        - "Calendar"
        - "Checkbox"
        - "Chips"
        - "Dropdown"
        - "InputGroup"
        - "InputMask"
        - "InputNumber"
        - "InputOtp"
        - "InputSwitch"
        - "InputText"
        - "Listbox"
        - "MultiSelect"
        - "Password"
        - "RadioButton"
        - "Rating"
        - "SelectButton"
        - "Slider"
        - "Textarea"
        - "ToggleButton"
        - "FloatLabel"
    validations:
      required: true

  - type: textarea
    id: what_to_change
    attributes:
      label: "Что изменить"
      description: "Укажите, что именно предлагается изменить"
      placeholder: "Опишите конкретные элементы, свойства или поведение компонента, которые требуют изменения"
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected_result
    attributes:
      label: "Ожидаемый результат"
      description: "Опишите ожидаемый результат от изменения"
      placeholder: "Как должен выглядеть или работать компонент после внесения изменений"
      render: markdown
    validations:
      required: true

  - type: textarea
    id: change_reason
    attributes:
      label: "Причина изменения"
      description: "Объясните, почему необходимо это изменение"
      placeholder: "Обоснуйте необходимость изменения: проблемы, которые решает, улучшения, которые приносит"
      render: markdown
    validations:
      required: true

  - type: input
    id: design_file
    attributes:
      label: "Ссылка на дизайн-файл"
      description: "Приложите ссылку на прототип с изменениями"
      placeholder: "https://figma.com/file/..."

  - type: dropdown
    id: change_type
    attributes:
      label: "Тип изменения"
      description: "Выберите тип предлагаемого изменения"
      options:
        - "Visual - изменение внешнего вида"
        - "Functional - изменение поведения"
        - "API - изменение интерфейса компонента"
        - "Performance - оптимизация производительности"
        - "Accessibility - улучшение доступности"
        - "Breaking - изменение с нарушением совместимости"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Приоритет изменения"
      description: "Укажите приоритет реализации изменения"
      options:
        - "Critical - блокирует текущую разработку"
        - "High - нужно в текущем спринте"
        - "Medium - планируется в ближайшие месяцы"
        - "Low"
    validations:
      required: true

  - type: textarea
    id: additional_details
    attributes:
      label: "Дополнительные детали"
      description: |
        Любая дополнительная информация:
        - Ссылки на исследования или примеры
        - Технические ограничения
        - Временные рамки
        - Другое
      placeholder: "Укажите дополнительную информацию..."
      render: markdown
