name: "Запрос на изменение компонента"
description: "Форма для запроса изменений в существующих компонентах дизайн-системы"
title: "[CHANGE] "
labels: ["type/enhancement", "status/needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Форма предназначена для сбора структурированной информации о необходимости изменения компонента в дизайн-системе.
        
        **Перед созданием запроса на изменение:**
        - Убедитесь, что изменение не нарушит существующую функциональность
        - Проверьте, не было ли уже создано похожего запроса
        - Подготовьте обоснование необходимости изменения
        
  - type: input
    id: title
    attributes:
      label: "Заголовок обращения"
      description: "Краткое описание предлагаемого изменения по шаблону {компонент}{изменение}"
      placeholder: "Например: Алерт: добавить возможность закрытия по таймеру"
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: "Компонент для изменения"
      description: "Выберите компонент, который требует изменений"
      options:
        - Button
        - Input
        - Alert
        - Modal
        - Card
        - Table
        - Navigation
        - Dropdown
        - Checkbox
        - Radio
        - Switch
        - Slider
        - Progress
        - Badge
        - Avatar
        - Tooltip
        - Popover
        - Other
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: "Подробное описание изменений"
      description: "Используйте структуру: [Изменить] → [Результат] → [Причина]"
      placeholder: |
        **[Изменить]:** Укажите, что именно предлагается изменить
        
        **[Результат]:** Опишите ожидаемый результат от изменения
        
        **[Причина]:** Объясните, почему необходимо это изменение
      render: markdown
    validations:
      required: true
      
  - type: input
    id: design_file
    attributes:
      label: "Ссылка на дизайн-файл"
      description: "Приложите ссылку на прототип с изменениями"
      placeholder: "https://figma.com/file/..."
      
  - type: dropdown
    id: change_type
    attributes:
      label: "Тип изменения"
      description: "Выберите тип предлагаемого изменения"
      options:
        - "Visual - изменение внешнего вида"
        - "Functional - изменение поведения"
        - "API - изменение интерфейса компонента"
        - "Performance - оптимизация производительности"
        - "Accessibility - улучшение доступности"
        - "Breaking - изменение с нарушением совместимости"
    validations:
      required: true
      
  - type: checkboxes
    id: affected_frameworks
    attributes:
      label: "Затронутые фреймворки"
      description: "В каких фреймворках требуется изменение"
      options:
        - label: "React"
          required: false
        - label: "Vue"
          required: false
        - label: "Angular"
          required: false
        - label: "React Native"
          required: false
        - label: "Vanilla JavaScript"
          required: false
          
  - type: dropdown
    id: priority
    attributes:
      label: "Приоритет изменения"
      description: "Укажите приоритет реализации изменения"
      options:
        - "Critical - блокирует текущую разработку"
        - "High - нужно в текущем спринте"
        - "Medium - планируется в ближайшие месяцы"
        - "Low - nice to have"
    validations:
      required: true
      
  - type: textarea
    id: backward_compatibility
    attributes:
      label: "Обратная совместимость"
      description: "Опишите влияние изменения на существующий код"
      placeholder: |
        - Будет ли изменение breaking change?
        - Какие части API затронуты?
        - Нужна ли миграция существующего кода?
        - Предлагаемая стратегия deprecation
      render: markdown
      
  - type: textarea
    id: additional_details
    attributes:
      label: "Дополнительные детали"
      description: |
        Любая дополнительная информация:
        - Ссылки на исследования или примеры
        - Технические ограничения
        - Временные рамки
        - Другие важные детали
      placeholder: "Укажите дополнительную информацию..."
      render: markdown